### ISSUE TITLE
Issue-Fix type 22words to 24

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#109]
Automated Review Comments
Issues in app/client/src/pages/Create.tsx:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in app/client/src/redux/appSlice.ts:
  - (9, 'Hardcoded string found')
Issues in app/server/controllers/mainController.js:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
Issues in app/server/controllers/socketController.js:
  - (4, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
