### ISSUE TITLE
Issue-Integrate live socket and test

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#111]
Automated Review Comments
Issues in app/client/src/pages/Dashboard.tsx:
  - (2, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
Issues in app/client/src/routes/ProtectedRoute.tsx:
  - (1, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
Issues in app/server/controllers/liveSocketController.js:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in app/server/controllers/socketController.js:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in app/server/managers/socketManager.js:
  - (5, 'Hardcoded string found')
Issues in app/server/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
