### ISSUE TITLE
Issue-Checking subshash

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#113]
Automated Review Comments
Issues in app/client/src/routes/ProtectedRoute.tsx:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in app/server/controllers/liveSocketController.js:
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in app/server/controllers/mainController.js:
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
