### ISSUE TITLE
Issue-Complete login process

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#117]
Automated Review Comments
Issues in app/client/src/context/SocketContext.tsx:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Dashboard.tsx:
  - (6, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (148, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (162, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (170, 'Line exceeds 80 characters')
  - (171, 'Line exceeds 80 characters')
  - (172, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (176, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
Issues in app/client/src/redux/appSlice.ts:
  - (4, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
Issues in app/server/controllers/liveSocketController.js:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in app/server/controllers/mainController.js:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
