### ISSUE TITLE
Issue-Add wasm

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#137]
Automated Review Comments
Issues in app/server/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in app/server/utils/a.out.worker.js:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
