### ISSUE TITLE
Issue-Implement restore

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#145]
Automated Review Comments
Issues in app/client/src/pages/Restore.tsx:
  - (2, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (122, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (124, 'Line exceeds 80 characters')
  - (125, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (145, 'Line exceeds 80 characters')
  - (146, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (150, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (152, 'Hardcoded string found')
  - (153, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (156, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (160, 'Hardcoded string found')
  - (161, 'Line exceeds 80 characters')
  - (161, 'Hardcoded string found')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (167, 'Line exceeds 80 characters')
  - (168, 'Line exceeds 80 characters')
  - (171, 'Hardcoded string found')
  - (173, 'Line exceeds 80 characters')
  - (173, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (178, 'Line exceeds 80 characters')
  - (179, 'Line exceeds 80 characters')
  - (180, 'Line exceeds 80 characters')
  - (181, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (188, 'Line exceeds 80 characters')
  - (188, 'Hardcoded string found')
  - (189, 'Line exceeds 80 characters')
  - (189, 'Hardcoded string found')
Issues in app/server/controllers/mainController.js:
  - (11, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
