### ISSUE TITLE
Issue-Transfer mock

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#147]
Automated Review Comments
Issues in app/client/src/pages/Dashboard.tsx:
  - (1, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (32, 'Hardcoded string found')
  - (41, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
