### ISSUE TITLE
Issue-Dev environment on server

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#151]
Automated Review Comments
Issues in app/server/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
