### ISSUE TITLE
Issue-Update addresses font family

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#153]
Automated Review Comments
Issues in app/client/src/pages/Dashboard.tsx:
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (10, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
