### ISSUE TITLE
Issue-Update dashboard ui

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#157]
Automated Review Comments
Issues in app/client/src/index.css:
  - (35, 'Hardcoded string found')
Issues in app/client/src/pages/Dashboard.tsx:
  - (11, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
