### ISSUE TITLE
Issue-transfer - 1

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#159]
Automated Review Comments
Issues in app/client/package-lock.json:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
Issues in app/client/package.json:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in app/client/src/pages/Dashboard.tsx:
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (125, 'Line exceeds 80 characters')
  - (126, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (139, 'Hardcoded string found')
  - (140, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (141, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (148, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (15, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
