### ISSUE TITLE
Issue-Integrate cli

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#161]
Automated Review Comments
Issues in app/client/src/pages/Cli.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
Issues in app/server/command.js:
  - (11, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in app/server/controllers/mainController.js:
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in app/server/controllers/socketController.js:
  - (5, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in app/server/dist/assets/index-B3pCxnKu.css:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/server/dist/assets/index-B9v5bBiW.css:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/server/dist/assets/index-BPvgi06w.css:
  - (2, 'Line exceeds 80 characters')
Issues in app/server/dist/assets/index-CFpMk0yC.css:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/server/dist/assets/index-CY9p1lJe.css:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/server/dist/assets/index-Ccy21s6Y.css:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/server/dist/assets/index-CdSm8tUF.css:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/server/dist/assets/index-DIzR-Pjx.css:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/server/dist/assets/index-Dhk6mmm9.css:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/server/dist/assets/index-DiwrgTda.css:
  - (2, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
