### ISSUE TITLE
Issue-Update cli

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#163]
Automated Review Comments
Issues in app/client/src/pages/Cli.tsx:
  - (5, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
Issues in app/server/dist/index.html:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
