### ISSUE TITLE
Issue-Install electron

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#173]
Automated Review Comments
Issues in app/server/package-lock.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (120, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (137, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (148, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (156, 'Line exceeds 80 characters')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
  - (178, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Line exceeds 80 characters')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Line exceeds 80 characters')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (210, 'Line exceeds 80 characters')
  - (210, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (217, 'Line exceeds 80 characters')
  - (217, 'Hardcoded string found')
  - (218, 'Line exceeds 80 characters')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (233, 'Line exceeds 80 characters')
  - (233, 'Hardcoded string found')
  - (234, 'Line exceeds 80 characters')
  - (234, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (242, 'Line exceeds 80 characters')
  - (242, 'Hardcoded string found')
  - (243, 'Line exceeds 80 characters')
  - (243, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (267, 'Line exceeds 80 characters')
  - (267, 'Hardcoded string found')
  - (268, 'Line exceeds 80 characters')
  - (268, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Line exceeds 80 characters')
  - (279, 'Hardcoded string found')
  - (280, 'Line exceeds 80 characters')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (288, 'Line exceeds 80 characters')
  - (288, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Line exceeds 80 characters')
  - (295, 'Hardcoded string found')
  - (296, 'Line exceeds 80 characters')
  - (296, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Line exceeds 80 characters')
  - (304, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Line exceeds 80 characters')
  - (311, 'Hardcoded string found')
  - (312, 'Line exceeds 80 characters')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (331, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (336, 'Line exceeds 80 characters')
  - (336, 'Hardcoded string found')
  - (337, 'Line exceeds 80 characters')
  - (337, 'Hardcoded string found')
  - (338, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (346, 'Line exceeds 80 characters')
  - (346, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Line exceeds 80 characters')
  - (351, 'Hardcoded string found')
  - (352, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (368, 'Line exceeds 80 characters')
  - (368, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (371, 'Line exceeds 80 characters')
  - (371, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (376, 'Line exceeds 80 characters')
  - (376, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (378, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (384, 'Line exceeds 80 characters')
  - (384, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (390, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (392, 'Line exceeds 80 characters')
  - (392, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (400, 'Line exceeds 80 characters')
  - (400, 'Hardcoded string found')
  - (401, 'Line exceeds 80 characters')
  - (401, 'Hardcoded string found')
  - (404, 'Hardcoded string found')
  - (405, 'Line exceeds 80 characters')
  - (405, 'Hardcoded string found')
  - (406, 'Line exceeds 80 characters')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (412, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (425, 'Line exceeds 80 characters')
  - (425, 'Hardcoded string found')
  - (426, 'Line exceeds 80 characters')
  - (426, 'Hardcoded string found')
  - (427, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (429, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (436, 'Hardcoded string found')
  - (437, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (446, 'Line exceeds 80 characters')
  - (446, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (448, 'Hardcoded string found')
  - (449, 'Hardcoded string found')
  - (451, 'Hardcoded string found')
  - (452, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (456, 'Hardcoded string found')
  - (461, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (463, 'Line exceeds 80 characters')
  - (463, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (467, 'Hardcoded string found')
  - (468, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (475, 'Hardcoded string found')
  - (476, 'Line exceeds 80 characters')
  - (476, 'Hardcoded string found')
  - (477, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (483, 'Hardcoded string found')
  - (484, 'Line exceeds 80 characters')
  - (484, 'Hardcoded string found')
  - (486, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (491, 'Line exceeds 80 characters')
  - (491, 'Hardcoded string found')
  - (492, 'Line exceeds 80 characters')
  - (492, 'Hardcoded string found')
  - (493, 'Hardcoded string found')
  - (494, 'Hardcoded string found')
  - (495, 'Hardcoded string found')
  - (497, 'Hardcoded string found')
  - (498, 'Hardcoded string found')
  - (500, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (505, 'Hardcoded string found')
  - (506, 'Line exceeds 80 characters')
  - (506, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (512, 'Hardcoded string found')
  - (513, 'Line exceeds 80 characters')
  - (513, 'Hardcoded string found')
  - (514, 'Line exceeds 80 characters')
  - (514, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (516, 'Hardcoded string found')
  - (517, 'Hardcoded string found')
  - (518, 'Hardcoded string found')
  - (520, 'Hardcoded string found')
  - (521, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (525, 'Hardcoded string found')
  - (526, 'Hardcoded string found')
  - (530, 'Hardcoded string found')
  - (531, 'Line exceeds 80 characters')
  - (531, 'Hardcoded string found')
  - (532, 'Line exceeds 80 characters')
  - (532, 'Hardcoded string found')
  - (533, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (535, 'Hardcoded string found')
  - (538, 'Hardcoded string found')
  - (539, 'Hardcoded string found')
  - (541, 'Hardcoded string found')
  - (542, 'Hardcoded string found')
  - (546, 'Hardcoded string found')
  - (547, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (553, 'Hardcoded string found')
  - (554, 'Hardcoded string found')
  - (555, 'Line exceeds 80 characters')
  - (555, 'Hardcoded string found')
  - (556, 'Hardcoded string found')
  - (557, 'Hardcoded string found')
  - (568, 'Hardcoded string found')
  - (570, 'Hardcoded string found')
  - (571, 'Hardcoded string found')
  - (573, 'Hardcoded string found')
  - (574, 'Hardcoded string found')
  - (578, 'Hardcoded string found')
  - (579, 'Line exceeds 80 characters')
  - (579, 'Hardcoded string found')
  - (581, 'Hardcoded string found')
  - (585, 'Hardcoded string found')
  - (586, 'Line exceeds 80 characters')
  - (586, 'Hardcoded string found')
  - (587, 'Line exceeds 80 characters')
  - (587, 'Hardcoded string found')
  - (588, 'Hardcoded string found')
  - (591, 'Hardcoded string found')
  - (592, 'Line exceeds 80 characters')
  - (592, 'Hardcoded string found')
  - (594, 'Hardcoded string found')
  - (598, 'Hardcoded string found')
  - (599, 'Line exceeds 80 characters')
  - (599, 'Hardcoded string found')
  - (600, 'Line exceeds 80 characters')
  - (600, 'Hardcoded string found')
  - (601, 'Hardcoded string found')
  - (602, 'Hardcoded string found')
  - (606, 'Hardcoded string found')
  - (607, 'Hardcoded string found')
  - (611, 'Hardcoded string found')
  - (612, 'Line exceeds 80 characters')
  - (612, 'Hardcoded string found')
  - (614, 'Hardcoded string found')
  - (618, 'Hardcoded string found')
  - (619, 'Line exceeds 80 characters')
  - (619, 'Hardcoded string found')
  - (620, 'Line exceeds 80 characters')
  - (620, 'Hardcoded string found')
  - (621, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (625, 'Line exceeds 80 characters')
  - (625, 'Hardcoded string found')
  - (626, 'Line exceeds 80 characters')
  - (626, 'Hardcoded string found')
  - (627, 'Hardcoded string found')
  - (628, 'Hardcoded string found')
  - (631, 'Hardcoded string found')
  - (632, 'Hardcoded string found')
  - (638, 'Hardcoded string found')
  - (639, 'Hardcoded string found')
  - (640, 'Line exceeds 80 characters')
  - (640, 'Hardcoded string found')
  - (641, 'Hardcoded string found')
  - (642, 'Hardcoded string found')
  - (647, 'Hardcoded string found')
  - (648, 'Line exceeds 80 characters')
  - (648, 'Hardcoded string found')
  - (649, 'Line exceeds 80 characters')
  - (649, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (651, 'Hardcoded string found')
  - (652, 'Hardcoded string found')
  - (656, 'Hardcoded string found')
  - (657, 'Hardcoded string found')
  - (659, 'Hardcoded string found')
  - (663, 'Hardcoded string found')
  - (664, 'Hardcoded string found')
  - (665, 'Line exceeds 80 characters')
  - (665, 'Hardcoded string found')
  - (666, 'Hardcoded string found')
  - (667, 'Hardcoded string found')
  - (668, 'Hardcoded string found')
  - (671, 'Hardcoded string found')
  - (672, 'Hardcoded string found')
  - (676, 'Hardcoded string found')
  - (677, 'Line exceeds 80 characters')
  - (677, 'Hardcoded string found')
  - (679, 'Hardcoded string found')
  - (683, 'Hardcoded string found')
  - (684, 'Line exceeds 80 characters')
  - (684, 'Hardcoded string found')
  - (685, 'Line exceeds 80 characters')
  - (685, 'Hardcoded string found')
  - (686, 'Hardcoded string found')
  - (687, 'Hardcoded string found')
  - (688, 'Hardcoded string found')
  - (690, 'Hardcoded string found')
  - (691, 'Hardcoded string found')
  - (695, 'Hardcoded string found')
  - (696, 'Line exceeds 80 characters')
  - (696, 'Hardcoded string found')
  - (698, 'Hardcoded string found')
  - (702, 'Hardcoded string found')
  - (703, 'Line exceeds 80 characters')
  - (703, 'Hardcoded string found')
  - (704, 'Line exceeds 80 characters')
  - (704, 'Hardcoded string found')
  - (705, 'Hardcoded string found')
  - (706, 'Hardcoded string found')
  - (707, 'Hardcoded string found')
  - (708, 'Hardcoded string found')
  - (712, 'Hardcoded string found')
  - (713, 'Line exceeds 80 characters')
  - (713, 'Hardcoded string found')
  - (715, 'Hardcoded string found')
  - (719, 'Hardcoded string found')
  - (720, 'Line exceeds 80 characters')
  - (720, 'Hardcoded string found')
  - (721, 'Line exceeds 80 characters')
  - (721, 'Hardcoded string found')
  - (722, 'Hardcoded string found')
  - (723, 'Hardcoded string found')
  - (724, 'Hardcoded string found')
  - (728, 'Hardcoded string found')
  - (729, 'Line exceeds 80 characters')
  - (729, 'Hardcoded string found')
  - (731, 'Hardcoded string found')
  - (735, 'Hardcoded string found')
  - (736, 'Hardcoded string found')
  - (737, 'Line exceeds 80 characters')
  - (737, 'Hardcoded string found')
  - (738, 'Hardcoded string found')
  - (741, 'Hardcoded string found')
  - (742, 'Hardcoded string found')
  - (748, 'Hardcoded string found')
  - (749, 'Hardcoded string found')
  - (750, 'Line exceeds 80 characters')
  - (750, 'Hardcoded string found')
  - (751, 'Hardcoded string found')
  - (752, 'Hardcoded string found')
  - (753, 'Hardcoded string found')
  - (755, 'Hardcoded string found')
  - (756, 'Hardcoded string found')
  - (760, 'Hardcoded string found')
  - (761, 'Line exceeds 80 characters')
  - (761, 'Hardcoded string found')
  - (763, 'Hardcoded string found')
  - (767, 'Hardcoded string found')
  - (768, 'Line exceeds 80 characters')
  - (768, 'Hardcoded string found')
  - (769, 'Line exceeds 80 characters')
  - (769, 'Hardcoded string found')
  - (770, 'Hardcoded string found')
  - (773, 'Hardcoded string found')
  - (774, 'Line exceeds 80 characters')
  - (774, 'Hardcoded string found')
  - (776, 'Hardcoded string found')
  - (780, 'Hardcoded string found')
  - (781, 'Line exceeds 80 characters')
  - (781, 'Hardcoded string found')
  - (782, 'Line exceeds 80 characters')
  - (782, 'Hardcoded string found')
  - (783, 'Hardcoded string found')
  - (784, 'Hardcoded string found')
  - (787, 'Hardcoded string found')
  - (788, 'Hardcoded string found')
  - (792, 'Hardcoded string found')
  - (793, 'Hardcoded string found')
  - (795, 'Hardcoded string found')
  - (799, 'Hardcoded string found')
  - (800, 'Hardcoded string found')
  - (801, 'Line exceeds 80 characters')
  - (801, 'Hardcoded string found')
  - (802, 'Hardcoded string found')
  - (803, 'Hardcoded string found')
  - (804, 'Hardcoded string found')
  - (805, 'Hardcoded string found')
  - (807, 'Hardcoded string found')
  - (812, 'Hardcoded string found')
  - (813, 'Hardcoded string found')
  - (817, 'Hardcoded string found')
  - (818, 'Line exceeds 80 characters')
  - (818, 'Hardcoded string found')
  - (820, 'Hardcoded string found')
  - (824, 'Hardcoded string found')
  - (825, 'Line exceeds 80 characters')
  - (825, 'Hardcoded string found')
  - (826, 'Line exceeds 80 characters')
  - (826, 'Hardcoded string found')
  - (827, 'Hardcoded string found')
  - (828, 'Hardcoded string found')
  - (831, 'Hardcoded string found')
  - (832, 'Hardcoded string found')
  - (834, 'Hardcoded string found')
  - (835, 'Line exceeds 80 characters')
  - (835, 'Hardcoded string found')
  - (838, 'Hardcoded string found')
  - (839, 'Line exceeds 80 characters')
  - (839, 'Hardcoded string found')
  - (840, 'Line exceeds 80 characters')
  - (840, 'Hardcoded string found')
  - (841, 'Hardcoded string found')
  - (842, 'Hardcoded string found')
  - (843, 'Hardcoded string found')
  - (846, 'Hardcoded string found')
  - (847, 'Hardcoded string found')
  - (849, 'Hardcoded string found')
  - (850, 'Hardcoded string found')
  - (854, 'Hardcoded string found')
  - (855, 'Line exceeds 80 characters')
  - (855, 'Hardcoded string found')
  - (857, 'Hardcoded string found')
  - (858, 'Line exceeds 80 characters')
  - (858, 'Hardcoded string found')
  - (861, 'Hardcoded string found')
  - (862, 'Line exceeds 80 characters')
  - (862, 'Hardcoded string found')
  - (863, 'Line exceeds 80 characters')
  - (863, 'Hardcoded string found')
  - (864, 'Hardcoded string found')
  - (865, 'Hardcoded string found')
  - (868, 'Hardcoded string found')
  - (869, 'Hardcoded string found')
  - (871, 'Hardcoded string found')
  - (875, 'Hardcoded string found')
  - (876, 'Line exceeds 80 characters')
  - (876, 'Hardcoded string found')
  - (877, 'Line exceeds 80 characters')
  - (877, 'Hardcoded string found')
  - (878, 'Hardcoded string found')
  - (879, 'Hardcoded string found')
  - (880, 'Hardcoded string found')
  - (882, 'Hardcoded string found')
  - (883, 'Hardcoded string found')
  - (887, 'Hardcoded string found')
  - (888, 'Hardcoded string found')
  - (889, 'Line exceeds 80 characters')
  - (889, 'Hardcoded string found')
  - (890, 'Hardcoded string found')
  - (891, 'Hardcoded string found')
  - (892, 'Hardcoded string found')
  - (894, 'Hardcoded string found')
  - (895, 'Hardcoded string found')
  - (897, 'Hardcoded string found')
  - (899, 'Hardcoded string found')
  - (904, 'Hardcoded string found')
  - (905, 'Hardcoded string found')
  - (906, 'Line exceeds 80 characters')
  - (906, 'Hardcoded string found')
  - (907, 'Hardcoded string found')
  - (910, 'Hardcoded string found')
  - (911, 'Line exceeds 80 characters')
  - (911, 'Hardcoded string found')
  - (913, 'Hardcoded string found')
  - (917, 'Hardcoded string found')
  - (918, 'Line exceeds 80 characters')
  - (918, 'Hardcoded string found')
  - (919, 'Line exceeds 80 characters')
  - (919, 'Hardcoded string found')
  - (920, 'Hardcoded string found')
  - (921, 'Hardcoded string found')
  - (922, 'Hardcoded string found')
  - (923, 'Hardcoded string found')
  - (925, 'Hardcoded string found')
  - (926, 'Hardcoded string found')
  - (930, 'Hardcoded string found')
  - (931, 'Hardcoded string found')
  - (933, 'Hardcoded string found')
  - (934, 'Hardcoded string found')
  - (938, 'Hardcoded string found')
  - (939, 'Hardcoded string found')
  - (940, 'Line exceeds 80 characters')
  - (940, 'Hardcoded string found')
  - (941, 'Hardcoded string found')
  - (942, 'Hardcoded string found')
Issues in app/server/package.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in app/server/server.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (45, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
