### ISSUE TITLE
Issue-Seperate electron and dev

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#183]
Automated Review Comments
Issues in app/server/main.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
Issues in app/server/package-lock.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Line exceeds 80 characters')
  - (121, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Line exceeds 80 characters')
  - (129, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Line exceeds 80 characters')
  - (141, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (152, 'Line exceeds 80 characters')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Line exceeds 80 characters')
  - (157, 'Hardcoded string found')
  - (158, 'Line exceeds 80 characters')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (172, 'Hardcoded string found')
  - (173, 'Line exceeds 80 characters')
  - (173, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (185, 'Line exceeds 80 characters')
  - (185, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (206, 'Line exceeds 80 characters')
  - (206, 'Hardcoded string found')
  - (207, 'Line exceeds 80 characters')
  - (207, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (211, 'Line exceeds 80 characters')
  - (211, 'Hardcoded string found')
Issues in app/server/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in app/server/server.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
Issues in app/server/utils/helpers.js:
  - (2, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
