### ISSUE TITLE
Issue-Update makefile

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#187]
Automated Review Comments
Issues in Makefile:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in app/server/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
