### ISSUE TITLE
Issue-Reset state

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#197]
Automated Review Comments
Issues in app/client/src/pages/Login.tsx:
  - (1, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
Issues in app/client/src/redux/appSlice.ts:
  - (3, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
