### ISSUE TITLE
Issue-Emit socket log

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#201]
Automated Review Comments
Issues in app/client/src/pages/Cli.tsx:
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
Issues in app/server/controllers/liveSocketController.js:
  - (5, 'Hardcoded string found')
Issues in app/server/controllers/mainController.js:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (98, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (141, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
Issues in app/server/controllers/socketController.js:
  - (3, 'Hardcoded string found')
Issues in app/server/main.js:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in app/server/managers/wasmManager.js:
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
