### ISSUE TITLE
Issue-Update login process

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#207]
Automated Review Comments
Issues in app/server/controllers/mainController.js:
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
