### ISSUE TITLE
Issue-Update balance

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#211]
Automated Review Comments
Issues in app/client/src/context/SocketContext.tsx:
  - (1, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Dashboard.tsx:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
Issues in app/client/src/redux/appSlice.ts:
  - (3, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
