### ISSUE TITLE
Issue-Update restore UI

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#215]
Automated Review Comments
Issues in app/client/src/pages/Restore.tsx:
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (95, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')

**Comment by ishida0415** [comment]
I got it.
