### ISSUE TITLE
Issue-Updated login process

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#223]
Automated Review Comments
Issues in app/server/controllers/mainController.js:
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
Issues in wasm.c:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
