### ISSUE TITLE
Issue-Merge pull request #18 from konan-5/app

Updated login process

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#225]
Automated Review Comments
Issues in wasm.c:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
