### ISSUE TITLE
Issue-Add cli socket debugging page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#233]
Automated Review Comments
Issues in app/client/src/pages/CliSocket.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
Issues in app/server/main.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in wasm.c:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
