### ISSUE TITLE
Issue-Merge pull request #2 from konan-5/feature/cli-socket

Add cli socket debugging page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#235]
Automated Review Comments
Issues in app/server/controllers/mainController.js:
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
