### ISSUE TITLE
Issue-Update transfer feature

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#245]
Automated Review Comments
Issues in app/server/controllers/mainController.js:
  - (10, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (98, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (133, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
