### ISSUE TITLE
Issue-Checking transfer

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#251]
Automated Review Comments
Issues in app/client/src/pages/Dashboard.tsx:
  - (3, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (137, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (154, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (157, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (3, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in wasm.c:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
