### ISSUE TITLE
Issue-Add activity pane

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#273]
Automated Review Comments
Issues in app/client/src/pages/Dashboard.tsx:
  - (34, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (114, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (126, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (140, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (143, 'Hardcoded string found')
  - (146, 'Line exceeds 80 characters')
  - (146, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (149, 'Hardcoded string found')
  - (152, 'Line exceeds 80 characters')
  - (152, 'Hardcoded string found')
  - (160, 'Line exceeds 80 characters')
  - (161, 'Line exceeds 80 characters')
  - (162, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (170, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (192, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
