### ISSUE TITLE
Issue-Updated responsive

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#277]
Automated Review Comments
Issues in app/client/src/pages/Dashboard.tsx:
  - (10, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
Issues in wasm.c:
  - (2, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
