### ISSUE TITLE
Issue-Add github workflow

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#299]
Automated Review Comments
Issues in .github/workflows/pr-main.yml:
  - (31, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
Issues in qarchiver.c:
  - (127, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (133, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (179, 'Line exceeds 80 characters')
  - (190, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (209, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (234, 'Line exceeds 80 characters')
  - (238, 'Line exceeds 80 characters')
  - (273, 'Line exceeds 80 characters')
  - (283, 'Line exceeds 80 characters')
  - (292, 'Hardcoded string found')
  - (310, 'Line exceeds 80 characters')
  - (313, 'Hardcoded string found')
  - (324, 'Line exceeds 80 characters')
  - (326, 'Line exceeds 80 characters')
  - (335, 'Hardcoded string found')
  - (339, 'Line exceeds 80 characters')
  - (340, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (404, 'Line exceeds 80 characters')
  - (407, 'Line exceeds 80 characters')
  - (411, 'Line exceeds 80 characters')
  - (423, 'Line exceeds 80 characters')
  - (424, 'Line exceeds 80 characters')
  - (437, 'Line exceeds 80 characters')
  - (441, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (459, 'Line exceeds 80 characters')
  - (488, 'Line exceeds 80 characters')
  - (490, 'Line exceeds 80 characters')
  - (492, 'Line exceeds 80 characters')
  - (494, 'Line exceeds 80 characters')
  - (496, 'Line exceeds 80 characters')
  - (498, 'Line exceeds 80 characters')
  - (500, 'Line exceeds 80 characters')
  - (502, 'Line exceeds 80 characters')
  - (512, 'Line exceeds 80 characters')
  - (515, 'Line exceeds 80 characters')
  - (517, 'Line exceeds 80 characters')
  - (522, 'Line exceeds 80 characters')
  - (526, 'Line exceeds 80 characters')
  - (541, 'Line exceeds 80 characters')
  - (545, 'Line exceeds 80 characters')
  - (553, 'Line exceeds 80 characters')
  - (565, 'Line exceeds 80 characters')
  - (566, 'Hardcoded string found')
  - (568, 'Line exceeds 80 characters')
  - (572, 'Line exceeds 80 characters')
  - (578, 'Line exceeds 80 characters')
  - (584, 'Hardcoded string found')
  - (597, 'Line exceeds 80 characters')
  - (599, 'Hardcoded string found')
  - (605, 'Line exceeds 80 characters')
  - (606, 'Line exceeds 80 characters')
  - (608, 'Line exceeds 80 characters')
  - (618, 'Line exceeds 80 characters')
  - (629, 'Line exceeds 80 characters')
  - (634, 'Line exceeds 80 characters')
  - (641, 'Line exceeds 80 characters')
  - (645, 'Line exceeds 80 characters')
  - (648, 'Line exceeds 80 characters')
  - (656, 'Line exceeds 80 characters')
  - (659, 'Line exceeds 80 characters')
  - (666, 'Line exceeds 80 characters')
  - (667, 'Hardcoded string found')
  - (670, 'Line exceeds 80 characters')
  - (674, 'Line exceeds 80 characters')
  - (675, 'Line exceeds 80 characters')
  - (676, 'Hardcoded string found')
  - (678, 'Hardcoded string found')
  - (679, 'Line exceeds 80 characters')
  - (682, 'Line exceeds 80 characters')
  - (684, 'Line exceeds 80 characters')
  - (685, 'Hardcoded string found')
  - (688, 'Line exceeds 80 characters')
  - (702, 'Line exceeds 80 characters')
  - (703, 'Line exceeds 80 characters')
  - (729, 'Line exceeds 80 characters')
  - (737, 'Line exceeds 80 characters')
  - (749, 'Line exceeds 80 characters')
  - (795, 'Line exceeds 80 characters')
  - (801, 'Hardcoded string found')
  - (809, 'Hardcoded string found')
  - (811, 'Line exceeds 80 characters')
  - (816, 'Line exceeds 80 characters')
  - (817, 'Hardcoded string found')
  - (820, 'Line exceeds 80 characters')
  - (826, 'Hardcoded string found')
  - (829, 'Line exceeds 80 characters')
  - (838, 'Line exceeds 80 characters')
  - (843, 'Line exceeds 80 characters')
  - (844, 'Hardcoded string found')
  - (854, 'Line exceeds 80 characters')
  - (855, 'Line exceeds 80 characters')
  - (858, 'Hardcoded string found')
  - (859, 'Hardcoded string found')
  - (864, 'Hardcoded string found')
  - (868, 'Line exceeds 80 characters')
  - (869, 'Hardcoded string found')
  - (911, 'Hardcoded string found')
  - (923, 'Hardcoded string found')
  - (924, 'Hardcoded string found')
  - (925, 'Hardcoded string found')
  - (945, 'Hardcoded string found')
Issues in qclient.c:
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (133, 'Line exceeds 80 characters')
  - (139, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (151, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (176, 'Line exceeds 80 characters')
  - (180, 'Line exceeds 80 characters')
  - (184, 'Line exceeds 80 characters')
  - (202, 'Line exceeds 80 characters')
  - (205, 'Line exceeds 80 characters')
  - (212, 'Line exceeds 80 characters')
  - (214, 'Hardcoded string found')
  - (223, 'Line exceeds 80 characters')
  - (229, 'Line exceeds 80 characters')
  - (240, 'Line exceeds 80 characters')
  - (259, 'Hardcoded string found')
  - (266, 'Line exceeds 80 characters')
  - (315, 'Line exceeds 80 characters')
  - (321, 'Hardcoded string found')
  - (335, 'Line exceeds 80 characters')
  - (349, 'Line exceeds 80 characters')
  - (366, 'Line exceeds 80 characters')
  - (390, 'Hardcoded string found')
  - (401, 'Line exceeds 80 characters')
  - (426, 'Hardcoded string found')
  - (456, 'Line exceeds 80 characters')
  - (457, 'Line exceeds 80 characters')
  - (484, 'Hardcoded string found')
  - (490, 'Line exceeds 80 characters')
  - (490, 'Hardcoded string found')
  - (498, 'Line exceeds 80 characters')
  - (500, 'Line exceeds 80 characters')
  - (515, 'Line exceeds 80 characters')
  - (551, 'Hardcoded string found')
  - (569, 'Line exceeds 80 characters')
  - (606, 'Hardcoded string found')
  - (623, 'Line exceeds 80 characters')
  - (636, 'Line exceeds 80 characters')
  - (651, 'Line exceeds 80 characters')
  - (666, 'Hardcoded string found')
  - (668, 'Line exceeds 80 characters')
  - (676, 'Hardcoded string found')
  - (694, 'Line exceeds 80 characters')
  - (697, 'Line exceeds 80 characters')
  - (713, 'Line exceeds 80 characters')
  - (721, 'Hardcoded string found')
  - (723, 'Line exceeds 80 characters')
  - (730, 'Line exceeds 80 characters')
  - (734, 'Line exceeds 80 characters')
  - (739, 'Line exceeds 80 characters')
  - (748, 'Line exceeds 80 characters')
  - (754, 'Line exceeds 80 characters')
  - (769, 'Hardcoded string found')
  - (773, 'Line exceeds 80 characters')
  - (777, 'Line exceeds 80 characters')
  - (779, 'Line exceeds 80 characters')
  - (783, 'Line exceeds 80 characters')
  - (801, 'Line exceeds 80 characters')
  - (812, 'Line exceeds 80 characters')
  - (814, 'Line exceeds 80 characters')
  - (818, 'Line exceeds 80 characters')
  - (819, 'Line exceeds 80 characters')
  - (820, 'Line exceeds 80 characters')
  - (821, 'Line exceeds 80 characters')
  - (822, 'Line exceeds 80 characters')
  - (824, 'Line exceeds 80 characters')
  - (830, 'Line exceeds 80 characters')
  - (831, 'Line exceeds 80 characters')
  - (832, 'Line exceeds 80 characters')
  - (834, 'Line exceeds 80 characters')
  - (835, 'Line exceeds 80 characters')
  - (836, 'Line exceeds 80 characters')
  - (841, 'Line exceeds 80 characters')
  - (844, 'Line exceeds 80 characters')
  - (846, 'Line exceeds 80 characters')
  - (848, 'Line exceeds 80 characters')
  - (849, 'Line exceeds 80 characters')
  - (850, 'Line exceeds 80 characters')
  - (855, 'Line exceeds 80 characters')
  - (858, 'Line exceeds 80 characters')
  - (875, 'Line exceeds 80 characters')
  - (883, 'Line exceeds 80 characters')
  - (905, 'Hardcoded string found')
  - (922, 'Hardcoded string found')
  - (929, 'Line exceeds 80 characters')
  - (929, 'Hardcoded string found')
  - (933, 'Line exceeds 80 characters')
  - (938, 'Line exceeds 80 characters')
  - (958, 'Hardcoded string found')
  - (971, 'Hardcoded string found')
  - (998, 'Line exceeds 80 characters')
  - (1024, 'Line exceeds 80 characters')
  - (1026, 'Line exceeds 80 characters')
  - (1049, 'Line exceeds 80 characters')
  - (1081, 'Hardcoded string found')
  - (1102, 'Line exceeds 80 characters')
  - (1103, 'Hardcoded string found')
  - (1107, 'Line exceeds 80 characters')
  - (1109, 'Line exceeds 80 characters')
  - (1128, 'Line exceeds 80 characters')
  - (1147, 'Hardcoded string found')
  - (1150, 'Hardcoded string found')
  - (1152, 'Line exceeds 80 characters')
  - (1161, 'Hardcoded string found')
  - (1172, 'Hardcoded string found')
  - (1181, 'Line exceeds 80 characters')
  - (1195, 'Line exceeds 80 characters')
  - (1198, 'Line exceeds 80 characters')
  - (1217, 'Hardcoded string found')
  - (1230, 'Hardcoded string found')
  - (1232, 'Line exceeds 80 characters')
  - (1232, 'Hardcoded string found')
  - (1234, 'Hardcoded string found')
  - (1236, 'Line exceeds 80 characters')
  - (1236, 'Hardcoded string found')
  - (1238, 'Hardcoded string found')
  - (1240, 'Hardcoded string found')
  - (1244, 'Hardcoded string found')
  - (1245, 'Hardcoded string found')
  - (1249, 'Line exceeds 80 characters')
  - (1251, 'Hardcoded string found')
  - (1255, 'Line exceeds 80 characters')
  - (1255, 'Hardcoded string found')
  - (1257, 'Hardcoded string found')
  - (1259, 'Hardcoded string found')
  - (1261, 'Hardcoded string found')
  - (1263, 'Hardcoded string found')
  - (1268, 'Line exceeds 80 characters')
  - (1270, 'Hardcoded string found')
  - (1274, 'Line exceeds 80 characters')
  - (1278, 'Line exceeds 80 characters')
  - (1294, 'Line exceeds 80 characters')
  - (1295, 'Line exceeds 80 characters')
  - (1303, 'Line exceeds 80 characters')
  - (1304, 'Line exceeds 80 characters')
  - (1308, 'Line exceeds 80 characters')
  - (1309, 'Line exceeds 80 characters')
  - (1321, 'Line exceeds 80 characters')
  - (1324, 'Line exceeds 80 characters')
  - (1337, 'Line exceeds 80 characters')
  - (1337, 'Hardcoded string found')
  - (1339, 'Line exceeds 80 characters')
  - (1352, 'Line exceeds 80 characters')
  - (1357, 'Line exceeds 80 characters')
  - (1360, 'Line exceeds 80 characters')
  - (1361, 'Line exceeds 80 characters')
  - (1374, 'Line exceeds 80 characters')
  - (1377, 'Line exceeds 80 characters')
Issues in qshared/json.c:
  - (1, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in qshared/qdefines.h:
  - (60, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
Issues in qshared/qhelpers.c:
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (218, 'Line exceeds 80 characters')
  - (248, 'Hardcoded string found')
  - (261, 'Hardcoded string found')
  - (265, 'Line exceeds 80 characters')
  - (267, 'Line exceeds 80 characters')
  - (288, 'Line exceeds 80 characters')
  - (288, 'Hardcoded string found')
Issues in qshared/qstructs.h:
  - (318, 'Line exceeds 80 characters')
  - (364, 'TODO found')
  - (379, 'TODO found')
  - (395, 'TODO found')
  - (424, 'TODO found')
  - (451, 'Line exceeds 80 characters')
  - (453, 'Line exceeds 80 characters')
Issues in qshared/qtx.c:
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
Issues in wasm.c:
  - (15, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (152, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (173, 'Line exceeds 80 characters')
  - (174, 'Line exceeds 80 characters')
  - (176, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (185, 'Line exceeds 80 characters')
  - (185, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (196, 'Line exceeds 80 characters')
  - (196, 'Hardcoded string found')
  - (197, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (206, 'Line exceeds 80 characters')
  - (206, 'Hardcoded string found')
  - (207, 'Line exceeds 80 characters')
  - (207, 'Hardcoded string found')
  - (225, 'Line exceeds 80 characters')
  - (226, 'Line exceeds 80 characters')
  - (228, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (326, 'Line exceeds 80 characters')
  - (333, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (377, 'Line exceeds 80 characters')
  - (381, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (388, 'Line exceeds 80 characters')
  - (388, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (390, 'Hardcoded string found')
  - (391, 'Line exceeds 80 characters')
  - (391, 'Hardcoded string found')
  - (392, 'Line exceeds 80 characters')
  - (392, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Line exceeds 80 characters')
  - (395, 'Hardcoded string found')
  - (396, 'Line exceeds 80 characters')
  - (396, 'Hardcoded string found')
  - (404, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (422, 'Line exceeds 80 characters')
  - (423, 'Line exceeds 80 characters')
  - (435, 'Hardcoded string found')
  - (443, 'Line exceeds 80 characters')
  - (447, 'Line exceeds 80 characters')
  - (465, 'Hardcoded string found')
  - (466, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
