### ISSUE TITLE
Issue-Updated github workflows

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#315]
Automated Review Comments
Issues in .github/workflows/pr-main.yml:
  - (7, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
