### ISSUE TITLE
Issue-Update workflow for keys directory

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#319]
Automated Review Comments
Issues in .github/workflows/pr-main.yml:
  - (7, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
