### ISSUE TITLE
Issue-Update checkavail code

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#354]
Automated Review Comments
Issues in app/server/controllers/mainController.js:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')

**Comment by ishida0415** [comment]
I got it.
