### ISSUE TITLE
Issue-feat: add main structure

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#360]
Automated Review Comments
Issues in mobile/package-lock.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (111, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (120, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Line exceeds 80 characters')
  - (129, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Line exceeds 80 characters')
  - (159, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (166, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (180, 'Line exceeds 80 characters')
  - (180, 'Hardcoded string found')
  - (181, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (185, 'Line exceeds 80 characters')
  - (185, 'Hardcoded string found')
  - (186, 'Line exceeds 80 characters')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Line exceeds 80 characters')
  - (204, 'Hardcoded string found')
  - (205, 'Line exceeds 80 characters')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (213, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Line exceeds 80 characters')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (252, 'Line exceeds 80 characters')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (264, 'Line exceeds 80 characters')
  - (264, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (271, 'Line exceeds 80 characters')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (276, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (288, 'Line exceeds 80 characters')
  - (288, 'Hardcoded string found')
  - (289, 'Line exceeds 80 characters')
  - (289, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (302, 'Line exceeds 80 characters')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Line exceeds 80 characters')
  - (315, 'Hardcoded string found')
  - (316, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Line exceeds 80 characters')
  - (329, 'Hardcoded string found')
  - (330, 'Line exceeds 80 characters')
  - (330, 'Hardcoded string found')
  - (331, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (338, 'Hardcoded string found')
  - (339, 'Line exceeds 80 characters')
  - (339, 'Hardcoded string found')
  - (340, 'Line exceeds 80 characters')
  - (340, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Line exceeds 80 characters')
  - (359, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (378, 'Hardcoded string found')
  - (379, 'Line exceeds 80 characters')
  - (379, 'Hardcoded string found')
  - (380, 'Line exceeds 80 characters')
  - (380, 'Hardcoded string found')
  - (381, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (388, 'Line exceeds 80 characters')
  - (388, 'Hardcoded string found')
  - (390, 'Line exceeds 80 characters')
  - (390, 'Hardcoded string found')
  - (391, 'Line exceeds 80 characters')
  - (391, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (396, 'Line exceeds 80 characters')
  - (396, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (402, 'Hardcoded string found')
  - (403, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (410, 'Line exceeds 80 characters')
  - (410, 'Hardcoded string found')
  - (411, 'Line exceeds 80 characters')
  - (411, 'Hardcoded string found')
  - (412, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (415, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (422, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (429, 'Line exceeds 80 characters')
  - (429, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (436, 'Hardcoded string found')
  - (437, 'Line exceeds 80 characters')
  - (437, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (440, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (445, 'Line exceeds 80 characters')
  - (445, 'Hardcoded string found')
  - (447, 'Line exceeds 80 characters')
  - (447, 'Hardcoded string found')
  - (448, 'Line exceeds 80 characters')
  - (448, 'Hardcoded string found')
  - (451, 'Hardcoded string found')
  - (452, 'Line exceeds 80 characters')
  - (452, 'Hardcoded string found')
  - (453, 'Line exceeds 80 characters')
  - (453, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (455, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (463, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (471, 'Line exceeds 80 characters')
  - (471, 'Hardcoded string found')
  - (472, 'Line exceeds 80 characters')
  - (472, 'Hardcoded string found')
  - (475, 'Hardcoded string found')
  - (476, 'Line exceeds 80 characters')
  - (476, 'Hardcoded string found')
  - (478, 'Line exceeds 80 characters')
  - (478, 'Hardcoded string found')
  - (479, 'Line exceeds 80 characters')
  - (479, 'Hardcoded string found')
  - (482, 'Hardcoded string found')
  - (483, 'Hardcoded string found')
  - (484, 'Line exceeds 80 characters')
  - (484, 'Hardcoded string found')
  - (485, 'Hardcoded string found')
  - (486, 'Hardcoded string found')
  - (487, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (494, 'Hardcoded string found')
  - (498, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (500, 'Line exceeds 80 characters')
  - (500, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (502, 'Hardcoded string found')
  - (503, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
  - (508, 'Line exceeds 80 characters')
  - (508, 'Hardcoded string found')
  - (510, 'Line exceeds 80 characters')
  - (510, 'Hardcoded string found')
  - (511, 'Line exceeds 80 characters')
  - (511, 'Hardcoded string found')
  - (514, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (516, 'Line exceeds 80 characters')
  - (516, 'Hardcoded string found')
  - (519, 'Hardcoded string found')
  - (520, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (526, 'Hardcoded string found')
  - (527, 'Line exceeds 80 characters')
  - (527, 'Hardcoded string found')
  - (528, 'Line exceeds 80 characters')
  - (528, 'Hardcoded string found')
  - (529, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (537, 'Line exceeds 80 characters')
  - (537, 'Hardcoded string found')
  - (539, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (544, 'Line exceeds 80 characters')
  - (544, 'Hardcoded string found')
  - (545, 'Line exceeds 80 characters')
  - (545, 'Hardcoded string found')
  - (546, 'Hardcoded string found')
  - (547, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (552, 'Hardcoded string found')
  - (553, 'Line exceeds 80 characters')
  - (553, 'Hardcoded string found')
  - (555, 'Hardcoded string found')
  - (559, 'Hardcoded string found')
  - (560, 'Line exceeds 80 characters')
  - (560, 'Hardcoded string found')
  - (561, 'Line exceeds 80 characters')
  - (561, 'Hardcoded string found')
  - (562, 'Hardcoded string found')
  - (563, 'Hardcoded string found')
  - (566, 'Hardcoded string found')
  - (568, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (571, 'Hardcoded string found')
  - (572, 'Hardcoded string found')
  - (576, 'Hardcoded string found')
  - (577, 'Line exceeds 80 characters')
  - (577, 'Hardcoded string found')
  - (578, 'Line exceeds 80 characters')
  - (578, 'Hardcoded string found')
  - (579, 'Hardcoded string found')
  - (580, 'Hardcoded string found')
  - (583, 'Hardcoded string found')
  - (584, 'Hardcoded string found')
  - (586, 'Hardcoded string found')
  - (587, 'Hardcoded string found')
  - (588, 'Hardcoded string found')
  - (590, 'Hardcoded string found')
  - (591, 'Hardcoded string found')
  - (595, 'Hardcoded string found')
  - (596, 'Line exceeds 80 characters')
  - (596, 'Hardcoded string found')
  - (597, 'Line exceeds 80 characters')
  - (597, 'Hardcoded string found')
  - (598, 'Hardcoded string found')
  - (599, 'Hardcoded string found')
  - (601, 'Hardcoded string found')
  - (602, 'Hardcoded string found')
  - (605, 'Hardcoded string found')
  - (606, 'Hardcoded string found')
  - (609, 'Hardcoded string found')
  - (610, 'Hardcoded string found')
  - (611, 'Hardcoded string found')
  - (613, 'Hardcoded string found')
  - (614, 'Hardcoded string found')
  - (616, 'Hardcoded string found')
  - (617, 'Hardcoded string found')
  - (620, 'Hardcoded string found')
  - (621, 'Hardcoded string found')
  - (622, 'Hardcoded string found')
  - (625, 'Hardcoded string found')
  - (630, 'Hardcoded string found')
  - (631, 'Hardcoded string found')
  - (632, 'Line exceeds 80 characters')
  - (632, 'Hardcoded string found')
  - (633, 'Hardcoded string found')
  - (634, 'Hardcoded string found')
  - (635, 'Hardcoded string found')
  - (637, 'Hardcoded string found')
  - (638, 'Hardcoded string found')
  - (642, 'Hardcoded string found')
  - (643, 'Line exceeds 80 characters')
  - (643, 'Hardcoded string found')
  - (644, 'Line exceeds 80 characters')
  - (644, 'Hardcoded string found')
  - (645, 'Hardcoded string found')
  - (646, 'Hardcoded string found')
  - (649, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (652, 'Hardcoded string found')
  - (653, 'Hardcoded string found')
  - (654, 'Hardcoded string found')
  - (656, 'Hardcoded string found')
  - (657, 'Hardcoded string found')
  - (661, 'Hardcoded string found')
  - (662, 'Line exceeds 80 characters')
  - (662, 'Hardcoded string found')
  - (663, 'Line exceeds 80 characters')
  - (663, 'Hardcoded string found')
  - (664, 'Hardcoded string found')
  - (665, 'Hardcoded string found')
  - (666, 'Hardcoded string found')
  - (669, 'Hardcoded string found')
  - (670, 'Hardcoded string found')
  - (674, 'Hardcoded string found')
  - (675, 'Line exceeds 80 characters')
  - (675, 'Hardcoded string found')
  - (677, 'Hardcoded string found')
  - (678, 'Line exceeds 80 characters')
  - (678, 'Hardcoded string found')
  - (681, 'Hardcoded string found')
  - (682, 'Line exceeds 80 characters')
  - (682, 'Hardcoded string found')
  - (683, 'Line exceeds 80 characters')
  - (683, 'Hardcoded string found')
  - (686, 'Hardcoded string found')
  - (687, 'Hardcoded string found')
  - (693, 'Hardcoded string found')
  - (694, 'Line exceeds 80 characters')
  - (694, 'Hardcoded string found')
  - (695, 'Line exceeds 80 characters')
  - (695, 'Hardcoded string found')
  - (696, 'Hardcoded string found')
  - (700, 'Hardcoded string found')
  - (702, 'Hardcoded string found')
  - (704, 'Hardcoded string found')
  - (706, 'Hardcoded string found')
  - (708, 'Hardcoded string found')
  - (711, 'Hardcoded string found')
  - (713, 'Hardcoded string found')
  - (714, 'Hardcoded string found')
  - (719, 'Hardcoded string found')
  - (720, 'Line exceeds 80 characters')
  - (720, 'Hardcoded string found')
  - (722, 'Hardcoded string found')
  - (726, 'Hardcoded string found')
  - (727, 'Line exceeds 80 characters')
  - (727, 'Hardcoded string found')
  - (728, 'Line exceeds 80 characters')
  - (728, 'Hardcoded string found')
  - (729, 'Hardcoded string found')
  - (732, 'Hardcoded string found')
  - (733, 'Hardcoded string found')
  - (735, 'Hardcoded string found')
  - (736, 'Hardcoded string found')
  - (740, 'Hardcoded string found')
  - (741, 'Line exceeds 80 characters')
  - (741, 'Hardcoded string found')
  - (742, 'Line exceeds 80 characters')
  - (742, 'Hardcoded string found')
  - (743, 'Hardcoded string found')
  - (747, 'Hardcoded string found')
  - (748, 'Hardcoded string found')
  - (750, 'Hardcoded string found')
  - (751, 'Hardcoded string found')
  - (756, 'Hardcoded string found')
  - (757, 'Line exceeds 80 characters')
  - (757, 'Hardcoded string found')
  - (759, 'Hardcoded string found')
  - (763, 'Hardcoded string found')
  - (764, 'Line exceeds 80 characters')
  - (764, 'Hardcoded string found')
  - (765, 'Line exceeds 80 characters')
  - (765, 'Hardcoded string found')
  - (766, 'Hardcoded string found')
  - (767, 'Hardcoded string found')
  - (768, 'Hardcoded string found')
  - (772, 'Hardcoded string found')
  - (773, 'Hardcoded string found')
  - (774, 'Line exceeds 80 characters')
  - (774, 'Hardcoded string found')
  - (775, 'Hardcoded string found')
  - (776, 'Hardcoded string found')
  - (777, 'Hardcoded string found')
  - (781, 'Hardcoded string found')
  - (782, 'Line exceeds 80 characters')
  - (782, 'Hardcoded string found')
  - (788, 'Hardcoded string found')
  - (789, 'Hardcoded string found')
  - (790, 'Line exceeds 80 characters')
  - (790, 'Hardcoded string found')
  - (791, 'Hardcoded string found')
  - (792, 'Hardcoded string found')
  - (793, 'Hardcoded string found')
  - (795, 'Hardcoded string found')
  - (796, 'Hardcoded string found')
  - (800, 'Hardcoded string found')
  - (801, 'Hardcoded string found')
  - (802, 'Line exceeds 80 characters')
  - (802, 'Hardcoded string found')
  - (803, 'Hardcoded string found')
  - (804, 'Hardcoded string found')
  - (805, 'Hardcoded string found')
  - (807, 'Hardcoded string found')
  - (808, 'Hardcoded string found')
  - (812, 'Hardcoded string found')
  - (813, 'Hardcoded string found')
  - (815, 'Hardcoded string found')
  - (819, 'Hardcoded string found')
  - (820, 'Hardcoded string found')
  - (821, 'Line exceeds 80 characters')
  - (821, 'Hardcoded string found')
  - (824, 'Hardcoded string found')
  - (825, 'Line exceeds 80 characters')
  - (825, 'Hardcoded string found')
  - (826, 'Line exceeds 80 characters')
  - (826, 'Hardcoded string found')
  - (827, 'Hardcoded string found')
  - (828, 'Hardcoded string found')
  - (832, 'Hardcoded string found')
  - (833, 'Line exceeds 80 characters')
  - (833, 'Hardcoded string found')
  - (839, 'Hardcoded string found')
  - (840, 'Hardcoded string found')
  - (841, 'Line exceeds 80 characters')
  - (841, 'Hardcoded string found')
  - (844, 'Hardcoded string found')
  - (845, 'Hardcoded string found')
  - (847, 'Hardcoded string found')
  - (851, 'Hardcoded string found')
  - (852, 'Line exceeds 80 characters')
  - (852, 'Hardcoded string found')
  - (853, 'Line exceeds 80 characters')
  - (853, 'Hardcoded string found')
  - (854, 'Hardcoded string found')
  - (855, 'Hardcoded string found')
  - (857, 'Hardcoded string found')
  - (858, 'Hardcoded string found')
  - (859, 'Hardcoded string found')
  - (860, 'Hardcoded string found')
  - (864, 'Hardcoded string found')
  - (865, 'Hardcoded string found')
  - (866, 'Hardcoded string found')
  - (869, 'Hardcoded string found')
  - (870, 'Hardcoded string found')
  - (876, 'Hardcoded string found')
  - (877, 'Hardcoded string found')
  - (879, 'Hardcoded string found')
  - (880, 'Hardcoded string found')
  - (881, 'Hardcoded string found')
  - (883, 'Hardcoded string found')
  - (884, 'Hardcoded string found')
  - (888, 'Hardcoded string found')
  - (889, 'Line exceeds 80 characters')
  - (889, 'Hardcoded string found')
  - (890, 'Line exceeds 80 characters')
  - (890, 'Hardcoded string found')
  - (891, 'Hardcoded string found')
  - (892, 'Hardcoded string found')
  - (895, 'Hardcoded string found')
  - (896, 'Hardcoded string found')
  - (900, 'Hardcoded string found')
  - (901, 'Hardcoded string found')
  - (903, 'Hardcoded string found')
  - (904, 'Line exceeds 80 characters')
  - (904, 'Hardcoded string found')
  - (907, 'Hardcoded string found')
  - (908, 'Hardcoded string found')
  - (909, 'Line exceeds 80 characters')
  - (909, 'Hardcoded string found')
  - (912, 'Hardcoded string found')
  - (913, 'Line exceeds 80 characters')
  - (913, 'Hardcoded string found')
  - (915, 'Hardcoded string found')
  - (919, 'Hardcoded string found')
  - (920, 'Line exceeds 80 characters')
  - (920, 'Hardcoded string found')
  - (921, 'Line exceeds 80 characters')
  - (921, 'Hardcoded string found')
  - (922, 'Hardcoded string found')
  - (927, 'Hardcoded string found')
  - (928, 'Line exceeds 80 characters')
  - (928, 'Hardcoded string found')
  - (930, 'Hardcoded string found')
  - (931, 'Line exceeds 80 characters')
  - (931, 'Hardcoded string found')
  - (934, 'Hardcoded string found')
  - (935, 'Line exceeds 80 characters')
  - (935, 'Hardcoded string found')
  - (936, 'Line exceeds 80 characters')
  - (936, 'Hardcoded string found')
  - (937, 'Hardcoded string found')
  - (938, 'Hardcoded string found')
  - (942, 'Hardcoded string found')
  - (943, 'Line exceeds 80 characters')
  - (943, 'Hardcoded string found')
  - (944, 'Line exceeds 80 characters')
  - (944, 'Hardcoded string found')
  - (945, 'Hardcoded string found')
  - (946, 'Hardcoded string found')
  - (949, 'Hardcoded string found')
  - (950, 'Hardcoded string found')
  - (954, 'Hardcoded string found')
  - (955, 'Line exceeds 80 characters')
  - (955, 'Hardcoded string found')
  - (957, 'Line exceeds 80 characters')
  - (957, 'Hardcoded string found')
  - (958, 'Line exceeds 80 characters')
  - (958, 'Hardcoded string found')
  - (961, 'Hardcoded string found')
  - (962, 'Line exceeds 80 characters')
  - (962, 'Hardcoded string found')
  - (963, 'Line exceeds 80 characters')
  - (963, 'Hardcoded string found')
  - (964, 'Hardcoded string found')
  - (965, 'Hardcoded string found')
  - (966, 'Hardcoded string found')
  - (970, 'Hardcoded string found')
  - (972, 'Hardcoded string found')
  - (973, 'Hardcoded string found')
  - (977, 'Hardcoded string found')
  - (978, 'Hardcoded string found')
  - (979, 'Line exceeds 80 characters')
  - (979, 'Hardcoded string found')
  - (980, 'Hardcoded string found')
  - (981, 'Hardcoded string found')
  - (985, 'Hardcoded string found')
  - (986, 'Hardcoded string found')
  - (987, 'Line exceeds 80 characters')
  - (987, 'Hardcoded string found')
  - (990, 'Hardcoded string found')
  - (991, 'Line exceeds 80 characters')
  - (991, 'Hardcoded string found')
  - (993, 'Hardcoded string found')
  - (997, 'Hardcoded string found')
  - (998, 'Hardcoded string found')
  - (999, 'Line exceeds 80 characters')
  - (999, 'Hardcoded string found')
  - (1000, 'Hardcoded string found')
  - (1001, 'Hardcoded string found')
  - (1005, 'Hardcoded string found')
  - (1006, 'Hardcoded string found')
Issues in mobile/package.json:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in mobile/src/pages/Backup.tsx:
  - (3, 'Hardcoded string found')
Issues in mobile/src/pages/Confirm.tsx:
  - (3, 'Hardcoded string found')
Issues in mobile/src/pages/Create.tsx:
  - (3, 'Hardcoded string found')
Issues in mobile/src/pages/Dashboard.tsx:
  - (3, 'Hardcoded string found')
Issues in mobile/src/pages/Login.tsx:
  - (3, 'Hardcoded string found')
Issues in mobile/src/pages/Restore.tsx:
  - (3, 'Hardcoded string found')
Issues in mobile/src/redux/appSlice.ts:
  - (10, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
Issues in mobile/src/routes/AppRoutes.tsx:
  - (3, 'Hardcoded string found')
Issues in mobile/src/routes/ProtectedRoute.tsx:
  - (3, 'Hardcoded string found')
Issues in mobile/src/utils/svg.tsx:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
Issues in mobile/tailwind.config.js:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
