### ISSUE TITLE
Issue-feat: Add Login UI

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#370]
Automated Review Comments
Issues in mobile/src/navigation/RootNavigation.tsx:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in mobile/src/screens/Login.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
