### ISSUE TITLE
Issue-chore: Login, Dashboard UI update

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#372]
Automated Review Comments
Issues in mobile/App.tsx:
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in mobile/src/screens/Dashboard.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (126, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
Issues in mobile/src/screens/Login.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (68, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
