### ISSUE TITLE
Issue-feat: Complete basic Login UI, Update Splash Image, Update Button Component

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#374]
Automated Review Comments
Issues in mobile/App.tsx:
  - (1, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in mobile/src/components/Button.tsx:
  - (2, 'Hardcoded string found')
Issues in mobile/src/screens/Dashboard.tsx:
  - (1, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
Issues in mobile/src/screens/Login.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (130, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
