### ISSUE TITLE
Issue-Merge branch 'main' of https://github.com/RealWorld777/Qwallet

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#378]
Automated Review Comments
Issues in app/server/controllers/mainController.js:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
