### ISSUE TITLE
Issue-feat: Add Input Component, Create Page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#386]
Automated Review Comments
Issues in README.md:
  - (1, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
Issues in mobile/App.tsx:
  - (11, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
Issues in mobile/package.json:
  - (3, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in mobile/src/components/Input.tsx:
  - (2, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
Issues in mobile/src/screens/Create.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
Issues in mobile/src/screens/Login.tsx:
  - (1, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (18, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
