### ISSUE TITLE
Issue-Update workflow for linux action

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#388]
Automated Review Comments
Issues in .github/workflows/pr-main.yml:
  - (4, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
Issues in app/client/src/App.tsx:
  - (2, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in app/client/src/pages/CliSocket.tsx:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
Issues in app/client/src/pages/Dashboard.tsx:
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Login.tsx:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/server/controllers/mainController.js:
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in app/server/managers/socketManager.js:
  - (6, 'Hardcoded string found')
Issues in mobile/App.tsx:
  - (12, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
Issues in mobile/package.json:
  - (3, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
