### ISSUE TITLE
Issue-refactor: Add Nativebase, refator Login, Create using Nativebase

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#418]
Automated Review Comments
Issues in README.md:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
Issues in mobile/App.tsx:
  - (13, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
Issues in mobile/package.json:
  - (3, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in mobile/src/screens/Create.tsx:
  - (2, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
Issues in mobile/src/screens/Login.tsx:
  - (2, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (159, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
