### ISSUE TITLE
Issue-chore: Update Login, Create screen styles

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#420]
Automated Review Comments
Issues in mobile/src/screens/Confirm.tsx:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in mobile/src/screens/Create.tsx:
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (17, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
