### ISSUE TITLE
Issue-fix: Create, Login Page Navigation, Add Confirm Screen

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#422]
Automated Review Comments
Issues in mobile/src/screens/Confirm.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
Issues in mobile/src/screens/Create.tsx:
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
