### ISSUE TITLE
Issue-feat: Add Restore Basic UI

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#430]
Automated Review Comments
Issues in mobile/src/screens/Restore.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (130, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
