### ISSUE TITLE
Issue-feat: Eject current project, Add baic background service

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#436]
Automated Review Comments
Issues in .github/workflows/pr-main.yml:
  - (4, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
Issues in README.md:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
Issues in app/client/src/App.tsx:
  - (2, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in app/client/src/pages/CliSocket.tsx:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
Issues in app/client/src/pages/Dashboard.tsx:
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Login.tsx:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/server/controllers/mainController.js:
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in app/server/managers/socketManager.js:
  - (6, 'Hardcoded string found')
Issues in mobile/App.tsx:
  - (6, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
Issues in mobile/android/app/build.gradle:
  - (10, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (125, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Line exceeds 80 characters')
  - (133, 'Line exceeds 80 characters')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Line exceeds 80 characters')
  - (151, 'Hardcoded string found')
  - (155, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (163, 'Line exceeds 80 characters')
  - (176, 'Line exceeds 80 characters')
  - (176, 'Hardcoded string found')
Issues in mobile/android/app/src/debug/AndroidManifest.xml:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
Issues in mobile/android/app/src/main/AndroidManifest.xml:
  - (12, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
Issues in mobile/android/app/src/main/java/com/anonymous/QWallet/MainActivity.kt:
  - (9, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
Issues in mobile/android/app/src/main/java/com/anonymous/QWallet/MainApplication.kt:
  - (29, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
Issues in mobile/android/app/src/main/res/drawable/rn_edit_text_material.xml:
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
