### ISSUE TITLE
Issue-feat: Construct background service - rn_bridge setting

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#452]
Automated Review Comments
Issues in .github/workflows/pr-main.yml:
  - (4, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
Issues in app/client/src/App.tsx:
  - (2, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in app/client/src/pages/CliSocket.tsx:
  - (1, 'Hardcoded string found')
  - (2, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
Issues in app/client/src/pages/Dashboard.tsx:
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (98, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (104, 'Hardcoded string found')
  - (112, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')
  - (122, 'Line exceeds 80 characters')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (134, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Login.tsx:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/client/src/redux/appSlice.ts:
  - (2, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
Issues in app/server/managers/socketManager.js:
  - (6, 'Hardcoded string found')
Issues in mobile/App.tsx:
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
Issues in mobile/app.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in mobile/nodejs-assets/nodejs-project/controller.js:
  - (17, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
Issues in mobile/nodejs-assets/nodejs-project/main.js:
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in mobile/nodejs-assets/nodejs-project/managers/socketManager.js:
  - (5, 'Hardcoded string found')
Issues in mobile/nodejs-assets/nodejs-project/managers/wasmManager.js:
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
Issues in mobile/nodejs-assets/nodejs-project/package.json:
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
Issues in mobile/nodejs-assets/nodejs-project/utils/helpers.js:
  - (2, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
Issues in mobile/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
Issues in mobile/src/api/user.ts:
  - (6, 'Hardcoded string found')
Issues in mobile/src/screens/Confirm.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
Issues in mobile/src/screens/Create.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
Issues in mobile/src/screens/Dashboard.tsx:
  - (16, 'Hardcoded string found')
Issues in mobile/src/screens/Login.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (149, 'Hardcoded string found')
  - (160, 'Line exceeds 80 characters')
  - (160, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
Issues in mobile/src/screens/Restore.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (130, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
