### ISSUE TITLE
Issue-feat: Implement Basic Login Logic

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#459]
Automated Review Comments
Issues in mobile/nodejs-assets/nodejs-project/main.js:
  - (1, 'Hardcoded string found')
Issues in mobile/package-lock.json:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
Issues in mobile/package.json:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in mobile/src/api/api.ts:
  - (2, 'Hardcoded string found')
Issues in mobile/src/context/AuthContext.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
Issues in mobile/src/screens/Login.tsx:
  - (1, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (56, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
