### ISSUE TITLE
Issue-Add richlist rank and real price

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#461]
Automated Review Comments
Issues in app/client/src/context/SocketContext.tsx:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Dashboard.tsx:
  - (1, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (124, 'Line exceeds 80 characters')
  - (132, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (140, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (143, 'Hardcoded string found')
  - (146, 'Line exceeds 80 characters')
  - (146, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (149, 'Hardcoded string found')
  - (157, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (161, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (169, 'Hardcoded string found')
  - (170, 'Line exceeds 80 characters')
  - (170, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (178, 'Line exceeds 80 characters')
  - (182, 'Line exceeds 80 characters')
  - (182, 'Hardcoded string found')
  - (183, 'Line exceeds 80 characters')
  - (183, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (191, 'Hardcoded string found')
  - (192, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (196, 'Line exceeds 80 characters')
  - (196, 'Hardcoded string found')
  - (199, 'Line exceeds 80 characters')
  - (199, 'Hardcoded string found')
  - (202, 'Line exceeds 80 characters')
  - (202, 'Hardcoded string found')
  - (205, 'Line exceeds 80 characters')
  - (205, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (216, 'Line exceeds 80 characters')
  - (217, 'Line exceeds 80 characters')
Issues in app/client/src/redux/appSlice.ts:
  - (21, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
Issues in mobile/App.tsx:
  - (6, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in mobile/app.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in mobile/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
Issues in mobile/src/screens/Confirm.tsx:
  - (2, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
Issues in mobile/src/screens/Create.tsx:
  - (2, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
Issues in mobile/src/screens/Dashboard.tsx:
  - (16, 'Hardcoded string found')
Issues in mobile/src/screens/Login.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (122, 'Line exceeds 80 characters')
  - (122, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (157, 'Line exceeds 80 characters')
  - (158, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
Issues in mobile/src/screens/Restore.tsx:
  - (2, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (125, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
