### ISSUE TITLE
Issue-Migrated app

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#47]
Automated Review Comments
Issues in app/public/a.out.worker.js:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
Issues in app/views/dashboard.ejs:
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
