### ISSUE TITLE
Issue-fix: Delete Permission Directory Sending from Frontend

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#473]
Automated Review Comments
Issues in mobile/nodejs-assets/nodejs-project/main.js:
  - (1, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
