### ISSUE TITLE
Issue-fix: fix Creating Error

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#477]
Automated Review Comments
Issues in mobile/nodejs-assets/nodejs-project/main.js:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
