### ISSUE TITLE
Issue-feat: Add Backup Page UI

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#481]
Automated Review Comments
Issues in mobile/nodejs-assets/nodejs-project/main.js:
  - (1, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in mobile/src/screens/Backup.tsx:
  - (3, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
Issues in mobile/src/screens/Create.tsx:
  - (9, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
