### ISSUE TITLE
Issue-feat: add page wrapper

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#485]
Automated Review Comments
Issues in mobile/src/components/PageWrapper.tsx:
  - (3, 'Hardcoded string found')
Issues in mobile/src/screens/Backup.tsx:
  - (3, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
