### ISSUE TITLE
Issue-Update for pkg

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#49]
Automated Review Comments
Issues in app/db/database.js:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in app/package-lock.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (112, 'Line exceeds 80 characters')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Line exceeds 80 characters')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Line exceeds 80 characters')
  - (146, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (149, 'Hardcoded string found')
  - (150, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Line exceeds 80 characters')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Line exceeds 80 characters')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Line exceeds 80 characters')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Line exceeds 80 characters')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (213, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Line exceeds 80 characters')
  - (222, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Line exceeds 80 characters')
  - (228, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (231, 'Line exceeds 80 characters')
  - (231, 'Hardcoded string found')
  - (232, 'Line exceeds 80 characters')
  - (232, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (244, 'Line exceeds 80 characters')
  - (244, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (264, 'Line exceeds 80 characters')
  - (264, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (267, 'Line exceeds 80 characters')
  - (267, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (276, 'Line exceeds 80 characters')
  - (276, 'Hardcoded string found')
  - (277, 'Line exceeds 80 characters')
  - (277, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Line exceeds 80 characters')
  - (279, 'Hardcoded string found')
  - (280, 'Line exceeds 80 characters')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (295, 'Line exceeds 80 characters')
  - (295, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (299, 'Line exceeds 80 characters')
  - (299, 'Hardcoded string found')
  - (300, 'Line exceeds 80 characters')
  - (300, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (302, 'Line exceeds 80 characters')
  - (302, 'Hardcoded string found')
  - (303, 'Line exceeds 80 characters')
  - (303, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (316, 'Line exceeds 80 characters')
  - (316, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (319, 'Line exceeds 80 characters')
  - (319, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Line exceeds 80 characters')
  - (328, 'Hardcoded string found')
  - (329, 'Line exceeds 80 characters')
  - (329, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (331, 'Line exceeds 80 characters')
  - (331, 'Hardcoded string found')
  - (332, 'Line exceeds 80 characters')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (341, 'Line exceeds 80 characters')
  - (341, 'Hardcoded string found')
  - (342, 'Line exceeds 80 characters')
  - (342, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (345, 'Line exceeds 80 characters')
  - (345, 'Hardcoded string found')
  - (346, 'Line exceeds 80 characters')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (352, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (364, 'Line exceeds 80 characters')
  - (364, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (373, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (378, 'Line exceeds 80 characters')
  - (378, 'Hardcoded string found')
Issues in app/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (22, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
