### ISSUE TITLE
Issue-feat: add Confirm page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#493]
Automated Review Comments
Issues in mobile/nodejs-assets/nodejs-project/main.js:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in mobile/src/screens/Backup.tsx:
  - (7, 'Hardcoded string found')
Issues in mobile/src/screens/Confirm.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
Issues in mobile/src/screens/Create.tsx:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
