### ISSUE TITLE
Issue-add Network Context

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#496]
Automated Review Comments
Issues in mobile/src/context/NetworkContext.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
Issues in mobile/src/context/SocketContext.tsx:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
Issues in mobile/src/screens/Dashboard.tsx:
  - (8, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
