### ISSUE TITLE
Issue-feat: Add New Slice

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#500]
Automated Review Comments
Issues in mobile/src/redux/appSlice.ts:
  - (21, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
