### ISSUE TITLE
Issue-fix: Bug fixin in socket refactoring

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#509]
Automated Review Comments
Issues in mobile/nodejs-assets/nodejs-project/controller.js:
  - (23, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in mobile/nodejs-assets/nodejs-project/main.js:
  - (5, 'Hardcoded string found')
Issues in mobile/nodejs-assets/nodejs-project/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in mobile/nodejs-assets/nodejs-project/utils/helpers.js:
  - (2, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
