### ISSUE TITLE
Issue-feat: Add UI components in Dashboard

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#512]
Automated Review Comments
Issues in mobile/App.tsx:
  - (8, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
Issues in mobile/package.json:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in mobile/src/context/NetworkContext.tsx:
  - (1, 'Line exceeds 80 characters')
Issues in mobile/src/screens/Dashboard.tsx:
  - (11, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Line exceeds 80 characters')
  - (193, 'Hardcoded string found')
  - (194, 'Line exceeds 80 characters')
  - (195, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Line exceeds 80 characters')
  - (207, 'Hardcoded string found')
  - (214, 'Line exceeds 80 characters')
  - (215, 'Line exceeds 80 characters')
  - (216, 'Line exceeds 80 characters')
  - (217, 'Line exceeds 80 characters')
  - (218, 'Line exceeds 80 characters')
  - (228, 'Line exceeds 80 characters')
  - (229, 'Hardcoded string found')
  - (233, 'Line exceeds 80 characters')
  - (234, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
Issues in mobile/src/screens/Login.tsx:
  - (5, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
