### ISSUE TITLE
Issue-feat: Add Backend Controllers

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#514]
Automated Review Comments
Issues in mobile/nodejs-assets/nodejs-project/controller.js:
  - (11, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
Issues in mobile/nodejs-assets/nodejs-project/main.js:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in mobile/src/screens/Dashboard.tsx:
  - (19, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
