### ISSUE TITLE
Issue-fix: module conflict error

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#516]
Automated Review Comments
Issues in mobile/nodejs-assets/nodejs-project/package-lock.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (276, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (378, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (403, 'Hardcoded string found')
  - (404, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (415, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (426, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (429, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (448, 'Hardcoded string found')
  - (449, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (452, 'Hardcoded string found')
  - (453, 'Hardcoded string found')
  - (457, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (463, 'Hardcoded string found')
  - (467, 'Hardcoded string found')
  - (468, 'Hardcoded string found')
  - (471, 'Hardcoded string found')
  - (472, 'Hardcoded string found')
  - (473, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (481, 'Hardcoded string found')
  - (485, 'Hardcoded string found')
  - (486, 'Hardcoded string found')
  - (489, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (497, 'Hardcoded string found')
  - (498, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (502, 'Hardcoded string found')
  - (506, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (509, 'Hardcoded string found')
  - (513, 'Hardcoded string found')
  - (514, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (518, 'Hardcoded string found')
  - (519, 'Hardcoded string found')
  - (523, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (527, 'Hardcoded string found')
  - (528, 'Hardcoded string found')
  - (529, 'Hardcoded string found')
  - (530, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (535, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (537, 'Hardcoded string found')
  - (541, 'Hardcoded string found')
  - (542, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (550, 'Hardcoded string found')
  - (553, 'Hardcoded string found')
  - (554, 'Hardcoded string found')
  - (558, 'Hardcoded string found')
  - (559, 'Hardcoded string found')
  - (560, 'Hardcoded string found')
  - (561, 'Hardcoded string found')
  - (565, 'Hardcoded string found')
  - (566, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (570, 'Hardcoded string found')
  - (571, 'Hardcoded string found')
  - (572, 'Hardcoded string found')
  - (575, 'Hardcoded string found')
  - (576, 'Hardcoded string found')
  - (580, 'Hardcoded string found')
  - (581, 'Hardcoded string found')
  - (582, 'Hardcoded string found')
  - (585, 'Hardcoded string found')
  - (586, 'Hardcoded string found')
  - (588, 'Hardcoded string found')
  - (589, 'Hardcoded string found')
  - (593, 'Hardcoded string found')
  - (594, 'Hardcoded string found')
  - (595, 'Hardcoded string found')
  - (596, 'Hardcoded string found')
  - (600, 'Hardcoded string found')
  - (601, 'Hardcoded string found')
  - (602, 'Hardcoded string found')
  - (603, 'Hardcoded string found')
  - (606, 'Hardcoded string found')
  - (608, 'Hardcoded string found')
  - (609, 'Hardcoded string found')
  - (613, 'Hardcoded string found')
  - (614, 'Hardcoded string found')
  - (616, 'Hardcoded string found')
  - (617, 'Hardcoded string found')
  - (620, 'Hardcoded string found')
  - (621, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (625, 'Hardcoded string found')
  - (628, 'Hardcoded string found')
  - (631, 'Hardcoded string found')
  - (632, 'Hardcoded string found')
  - (635, 'Hardcoded string found')
  - (636, 'Hardcoded string found')
  - (637, 'Hardcoded string found')
  - (638, 'Hardcoded string found')
  - (639, 'Hardcoded string found')
  - (640, 'Hardcoded string found')
  - (641, 'Hardcoded string found')
  - (643, 'Hardcoded string found')
  - (644, 'Hardcoded string found')
  - (646, 'Hardcoded string found')
  - (647, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (652, 'Hardcoded string found')
  - (653, 'Hardcoded string found')
  - (657, 'Hardcoded string found')
  - (658, 'Hardcoded string found')
  - (661, 'Hardcoded string found')
  - (662, 'Hardcoded string found')
  - (663, 'Hardcoded string found')
  - (664, 'Hardcoded string found')
  - (666, 'Hardcoded string found')
  - (667, 'Hardcoded string found')
  - (669, 'Hardcoded string found')
  - (670, 'Hardcoded string found')
  - (674, 'Hardcoded string found')
  - (675, 'Hardcoded string found')
  - (676, 'Hardcoded string found')
  - (681, 'Hardcoded string found')
  - (684, 'Hardcoded string found')
  - (685, 'Hardcoded string found')
  - (689, 'Hardcoded string found')
  - (690, 'Hardcoded string found')
  - (693, 'Hardcoded string found')
  - (694, 'Hardcoded string found')
  - (695, 'Hardcoded string found')
  - (701, 'Hardcoded string found')
  - (702, 'Hardcoded string found')
  - (704, 'Hardcoded string found')
  - (705, 'Hardcoded string found')
  - (709, 'Hardcoded string found')
  - (710, 'Hardcoded string found')
  - (711, 'Line exceeds 80 characters')
  - (711, 'Hardcoded string found')
  - (712, 'Hardcoded string found')
  - (713, 'Hardcoded string found')
  - (715, 'Hardcoded string found')
  - (716, 'Hardcoded string found')
  - (721, 'Hardcoded string found')
  - (722, 'Hardcoded string found')
  - (726, 'Hardcoded string found')
  - (727, 'Hardcoded string found')
  - (728, 'Hardcoded string found')
  - (729, 'Hardcoded string found')
  - (730, 'Hardcoded string found')
  - (734, 'Hardcoded string found')
  - (735, 'Hardcoded string found')
  - (736, 'Hardcoded string found')
  - (737, 'Hardcoded string found')
  - (739, 'Hardcoded string found')
  - (740, 'Hardcoded string found')
  - (742, 'Hardcoded string found')
  - (744, 'Hardcoded string found')
  - (749, 'Hardcoded string found')
  - (750, 'Hardcoded string found')
  - (753, 'Hardcoded string found')
  - (754, 'Hardcoded string found')
  - (755, 'Hardcoded string found')
  - (757, 'Hardcoded string found')
  - (761, 'Hardcoded string found')
  - (762, 'Hardcoded string found')
  - (766, 'Hardcoded string found')
  - (767, 'Hardcoded string found')
  - (768, 'Hardcoded string found')
  - (769, 'Hardcoded string found')
  - (771, 'Hardcoded string found')
  - (772, 'Hardcoded string found')
  - (774, 'Hardcoded string found')
  - (776, 'Hardcoded string found')
  - (781, 'Hardcoded string found')
  - (782, 'Hardcoded string found')
  - (785, 'Hardcoded string found')
  - (786, 'Hardcoded string found')
  - (787, 'Hardcoded string found')
  - (789, 'Hardcoded string found')
  - (791, 'Hardcoded string found')
  - (792, 'Hardcoded string found')
  - (796, 'Hardcoded string found')
  - (797, 'Hardcoded string found')
  - (798, 'Hardcoded string found')
  - (799, 'Hardcoded string found')
  - (801, 'Hardcoded string found')
  - (802, 'Hardcoded string found')
  - (804, 'Hardcoded string found')
  - (806, 'Hardcoded string found')
  - (811, 'Hardcoded string found')
  - (812, 'Hardcoded string found')
  - (815, 'Hardcoded string found')
  - (816, 'Hardcoded string found')
  - (817, 'Hardcoded string found')
  - (818, 'Hardcoded string found')
  - (820, 'Hardcoded string found')
  - (821, 'Hardcoded string found')
  - (823, 'Hardcoded string found')
  - (825, 'Hardcoded string found')
  - (830, 'Hardcoded string found')
  - (831, 'Hardcoded string found')
  - (834, 'Hardcoded string found')
  - (835, 'Hardcoded string found')
  - (836, 'Hardcoded string found')
  - (837, 'Hardcoded string found')
  - (841, 'Hardcoded string found')
  - (842, 'Hardcoded string found')
  - (843, 'Hardcoded string found')
  - (844, 'Hardcoded string found')
  - (848, 'Hardcoded string found')
  - (849, 'Hardcoded string found')
  - (850, 'Hardcoded string found')
  - (854, 'Hardcoded string found')
  - (855, 'Hardcoded string found')
  - (859, 'Hardcoded string found')
  - (860, 'Hardcoded string found')
  - (863, 'Hardcoded string found')
  - (864, 'Hardcoded string found')
  - (865, 'Hardcoded string found')
  - (866, 'Hardcoded string found')
  - (870, 'Hardcoded string found')
  - (871, 'Hardcoded string found')
  - (872, 'Hardcoded string found')
  - (873, 'Hardcoded string found')
  - (877, 'Hardcoded string found')
  - (878, 'Hardcoded string found')
  - (879, 'Hardcoded string found')
  - (880, 'Hardcoded string found')
  - (881, 'Hardcoded string found')
  - (885, 'Hardcoded string found')
  - (886, 'Hardcoded string found')
  - (887, 'Hardcoded string found')
  - (888, 'Hardcoded string found')
  - (889, 'Line exceeds 80 characters')
  - (889, 'Hardcoded string found')
  - (890, 'Hardcoded string found')
  - (891, 'Hardcoded string found')
  - (893, 'Hardcoded string found')
  - (894, 'Hardcoded string found')
  - (898, 'Hardcoded string found')
  - (899, 'Hardcoded string found')
  - (901, 'Hardcoded string found')
  - (906, 'Hardcoded string found')
  - (907, 'Hardcoded string found')
  - (908, 'Hardcoded string found')
Issues in mobile/src/navigation/RootNavigation.tsx:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
