### ISSUE TITLE
Issue-fix: remove uncompatible tailwindcss, add getToken logic

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#523]
Automated Review Comments
Issues in mobile/nodejs-assets/nodejs-project/controller.js:
  - (2, 'Hardcoded string found')
Issues in mobile/src/components/NetworkSwitcher.tsx:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in mobile/src/screens/Dashboard.tsx:
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (137, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (141, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (176, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (178, 'Line exceeds 80 characters')
  - (179, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Line exceeds 80 characters')
  - (184, 'Line exceeds 80 characters')
  - (190, 'Hardcoded string found')
  - (201, 'Line exceeds 80 characters')
  - (202, 'Line exceeds 80 characters')
  - (203, 'Hardcoded string found')
  - (207, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (209, 'Hardcoded string found')
  - (211, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
