### ISSUE TITLE
Issue-feat: Add Transfer Logic in Dashboard, UI correction

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#525]
Automated Review Comments
Issues in mobile/src/api/api.ts:
  - (5, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
Issues in mobile/src/api/eventEmitter.ts:
  - (2, 'Hardcoded string found')
Issues in mobile/src/components/NetworkSwitcher.tsx:
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in mobile/src/components/SocketComponent.tsx:
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in mobile/src/screens/Dashboard.tsx:
  - (42, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (174, 'Line exceeds 80 characters')
  - (188, 'Line exceeds 80 characters')
  - (190, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (203, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (305, 'Line exceeds 80 characters')
  - (306, 'Line exceeds 80 characters')
  - (309, 'Hardcoded string found')
  - (312, 'Line exceeds 80 characters')
  - (313, 'Hardcoded string found')
  - (316, 'Hardcoded string found')
  - (318, 'Line exceeds 80 characters')
  - (323, 'Hardcoded string found')
  - (325, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (358, 'Line exceeds 80 characters')
  - (361, 'Hardcoded string found')
  - (362, 'Line exceeds 80 characters')
  - (363, 'Hardcoded string found')
  - (364, 'Line exceeds 80 characters')
  - (367, 'Hardcoded string found')
  - (368, 'Line exceeds 80 characters')
  - (374, 'Hardcoded string found')
  - (375, 'Line exceeds 80 characters')
  - (376, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (380, 'Line exceeds 80 characters')
  - (389, 'Hardcoded string found')
  - (403, 'Line exceeds 80 characters')
  - (404, 'Hardcoded string found')
  - (408, 'Line exceeds 80 characters')
  - (409, 'Hardcoded string found')
  - (411, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
