### ISSUE TITLE
Issue-refactor: Dashboard Token List UI refactor

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#527]
Automated Review Comments
Issues in mobile/src/screens/Dashboard.tsx:
  - (19, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')

**Comment by ishida0415** [comment]
I got it.
