### ISSUE TITLE
Issue-feat: Add 3 Modal in Dashboard

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#549]
Automated Review Comments
Issues in mobile/src/screens/Dashboard.tsx:
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (261, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Line exceeds 80 characters')
  - (286, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (311, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
