### ISSUE TITLE
Issue-fix: Delete unnecessary Address Modal

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#551]
Automated Review Comments
Issues in mobile/src/screens/Dashboard.tsx:
  - (47, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (109, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
