### ISSUE TITLE
Issue-feat: Add document directory path init

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#553]
Automated Review Comments
Issues in mobile/nodejs-assets/nodejs-project/main.js:
  - (1, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
Issues in mobile/src/api/api.ts:
  - (11, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
