### ISSUE TITLE
Issue-feat: Update Restore Feature, Sync with desktop

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#557]
Automated Review Comments
Issues in mobile/nodejs-assets/nodejs-project/controller.js:
  - (1, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
Issues in mobile/src/api/api.ts:
  - (12, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in mobile/src/screens/Restore.tsx:
  - (2, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (127, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (212, 'Line exceeds 80 characters')
  - (212, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (219, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (285, 'Line exceeds 80 characters')
  - (289, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (324, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
