### ISSUE TITLE
Issue-refactor: some UI updates in Restore

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#559]
Automated Review Comments
Issues in mobile/src/screens/Restore.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
  - (243, 'Line exceeds 80 characters')
  - (247, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (266, 'Line exceeds 80 characters')
  - (278, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (293, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
