### ISSUE TITLE
Issue-feat: add splitting apk for platform in build.gradle

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#563]
Automated Review Comments
Issues in mobile/android/app/build.gradle:
  - (2, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')

**Comment by ishida0415** [comment]
I got it.
