### ISSUE TITLE
Issue-fix: delete modal error

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#583]
Automated Review Comments
Issues in app/client/index.html:
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in app/client/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
Issues in app/client/src/App.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in app/client/src/index.css:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
Issues in app/client/src/main.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in app/client/src/pages/Dashboard.tsx:
  - (7, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (181, 'Line exceeds 80 characters')
  - (182, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (191, 'Line exceeds 80 characters')
  - (234, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (249, 'Line exceeds 80 characters')
  - (252, 'Line exceeds 80 characters')
  - (253, 'Line exceeds 80 characters')
  - (257, 'Line exceeds 80 characters')
  - (258, 'Line exceeds 80 characters')
  - (262, 'Line exceeds 80 characters')
  - (264, 'Line exceeds 80 characters')
  - (265, 'Line exceeds 80 characters')
  - (269, 'Line exceeds 80 characters')
  - (271, 'Line exceeds 80 characters')
  - (273, 'Line exceeds 80 characters')
  - (277, 'Line exceeds 80 characters')
  - (278, 'Line exceeds 80 characters')
  - (279, 'Line exceeds 80 characters')
  - (284, 'Line exceeds 80 characters')
  - (285, 'Line exceeds 80 characters')
  - (287, 'Line exceeds 80 characters')
  - (288, 'Line exceeds 80 characters')
  - (289, 'Hardcoded string found')
  - (290, 'Line exceeds 80 characters')
  - (290, 'Hardcoded string found')
  - (296, 'Line exceeds 80 characters')
  - (309, 'Line exceeds 80 characters')
  - (309, 'Hardcoded string found')
  - (310, 'Line exceeds 80 characters')
  - (310, 'Hardcoded string found')
  - (311, 'Line exceeds 80 characters')
  - (315, 'Line exceeds 80 characters')
  - (315, 'Hardcoded string found')
  - (316, 'Line exceeds 80 characters')
  - (316, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (320, 'Line exceeds 80 characters')
  - (323, 'Line exceeds 80 characters')
  - (324, 'Line exceeds 80 characters')
  - (328, 'Line exceeds 80 characters')
  - (328, 'Hardcoded string found')
  - (329, 'Line exceeds 80 characters')
  - (329, 'Hardcoded string found')
  - (330, 'Line exceeds 80 characters')
  - (337, 'Hardcoded string found')
  - (338, 'Line exceeds 80 characters')
  - (339, 'Line exceeds 80 characters')
  - (342, 'Line exceeds 80 characters')
  - (342, 'Hardcoded string found')
  - (345, 'Line exceeds 80 characters')
  - (345, 'Hardcoded string found')
  - (348, 'Line exceeds 80 characters')
  - (348, 'Hardcoded string found')
  - (351, 'Line exceeds 80 characters')
  - (351, 'Hardcoded string found')
  - (359, 'Line exceeds 80 characters')
  - (360, 'Line exceeds 80 characters')
  - (361, 'Line exceeds 80 characters')
  - (362, 'Line exceeds 80 characters')
  - (363, 'Line exceeds 80 characters')
  - (378, 'Line exceeds 80 characters')
  - (381, 'Line exceeds 80 characters')
  - (382, 'Line exceeds 80 characters')
  - (385, 'Line exceeds 80 characters')
  - (389, 'Line exceeds 80 characters')
  - (390, 'Line exceeds 80 characters')
  - (391, 'Line exceeds 80 characters')
  - (392, 'Line exceeds 80 characters')
  - (399, 'Line exceeds 80 characters')
  - (402, 'Line exceeds 80 characters')
  - (405, 'Line exceeds 80 characters')
  - (408, 'Line exceeds 80 characters')
  - (409, 'Line exceeds 80 characters')
  - (415, 'Line exceeds 80 characters')
  - (415, 'Hardcoded string found')
  - (416, 'Line exceeds 80 characters')
  - (417, 'Hardcoded string found')
  - (419, 'Line exceeds 80 characters')
  - (419, 'Hardcoded string found')
  - (422, 'Line exceeds 80 characters')
  - (427, 'Hardcoded string found')
  - (428, 'Line exceeds 80 characters')
  - (433, 'Hardcoded string found')
  - (434, 'Line exceeds 80 characters')
  - (435, 'Line exceeds 80 characters')
  - (436, 'Line exceeds 80 characters')
  - (438, 'Hardcoded string found')
  - (440, 'Line exceeds 80 characters')
  - (441, 'Line exceeds 80 characters')
  - (446, 'Line exceeds 80 characters')
  - (449, 'Line exceeds 80 characters')
  - (454, 'Line exceeds 80 characters')
Issues in app/client/src/routes/AppRoutes.tsx:
  - (2, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
Issues in app/client/src/routes/ProtectedRoute.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
Issues in app/client/src/utils/constants.ts:
  - (2, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
Issues in app/client/tailwind.config.js:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
Issues in mobile/android/app/build.gradle:
  - (14, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
Issues in mobile/android/app/src/main/AndroidManifest.xml:
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in mobile/android/app/src/main/java/com/qsilver/qwallet/MainActivity.kt:
  - (9, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
Issues in mobile/android/app/src/main/java/com/qsilver/qwallet/MainApplication.kt:
  - (29, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
Issues in mobile/app.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in mobile/src/screens/Dashboard.tsx:
  - (10, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
Issues in qserver/qpeers.c:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
Issues in qserver/qserver.c:
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (96, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (97, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (111, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (120, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (121, 'Line exceeds 80 characters')
  - (121, 'Hardcoded string found')
  - (122, 'Line exceeds 80 characters')
  - (122, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (140, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (184, 'Line exceeds 80 characters')
  - (192, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
Issues in qserver/qx.c:
  - (1, 'Line exceeds 80 characters')
Issues in qshared/qtx.c:
  - (1, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
