### ISSUE TITLE
Issue-feat: Restore UI update

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#601]
Automated Review Comments
Issues in mobile/src/screens/Backup.tsx:
  - (1, 'Hardcoded string found')
Issues in mobile/src/screens/Restore.tsx:
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
