### ISSUE TITLE
Issue-password and signup validations

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#605]
Automated Review Comments
Issues in app/client/package-lock.json:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
Issues in app/client/package.json:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in app/client/src/App.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in app/client/src/components/layout/Navbar.tsx:
  - (2, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
Issues in app/client/src/contexts/AuthContext.tsx:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Dashboard.tsx:
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Login/Login.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/AccountOptions.tsx:
  - (20, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/SignUp.tsx:
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/SignUpSeeds.tsx:
  - (2, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
Issues in app/client/src/routes/AppRoutes.tsx:
  - (9, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
Issues in mobile/android/app/src/main/AndroidManifest.xml:
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in mobile/app.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in mobile/nodejs-assets/nodejs-project/main.js:
  - (1, 'Hardcoded string found')
Issues in mobile/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in mobile/src/screens/Backup.tsx:
  - (1, 'Hardcoded string found')
Issues in mobile/src/screens/Dashboard.tsx:
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
Issues in mobile/src/screens/Restore.tsx:
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
