### ISSUE TITLE
Issue-Merge branch 'main' into layout

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#615]
Automated Review Comments
Issues in public/index.html:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in src/components/Layout/index.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/config/tokens.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
Issues in src/contexts/accounts.tsx:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/contexts/connection.tsx:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/contexts/market.tsx:
  - (2, 'Hardcoded string found')
Issues in src/contexts/wallet.tsx:
  - (5, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
Issues in src/index.css:
  - (2, 'Hardcoded string found')
Issues in src/manifest.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/views/faucet/index.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
Issues in src/views/home/index.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'TODO found')
  - (40, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
