### ISSUE TITLE
Issue-Update maincontroller

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#619]
Automated Review Comments
Issues in app/server/controllers/mainController.js:
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
