### ISSUE TITLE
Issue-Implement updated UI

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#640]
Automated Review Comments
Issues in app/client/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in app/client/public/assets/images/signup/eye.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
Issues in app/client/src/components/commons/Text.tsx:
  - (1, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/Summary.tsx:
  - (1, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/SummaryItem.tsx:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/SwitchButton.tsx:
  - (2, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/TokenComponent.tsx:
  - (2, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/select/TokenSelect.tsx:
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/InnerContainer.tsx:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/Navbar.tsx:
  - (2, 'Hardcoded string found')
Issues in app/client/src/components/layout/Sidebar.tsx:
  - (19, 'Hardcoded string found')
Issues in app/client/src/contexts/AuthContext.tsx:
  - (4, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (137, 'Line exceeds 80 characters')
  - (194, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (211, 'Line exceeds 80 characters')
  - (222, 'Line exceeds 80 characters')
  - (237, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Accounts/Accounts.tsx:
  - (14, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (173, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (204, 'Line exceeds 80 characters')
  - (204, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
Issues in app/client/src/pages/Settings.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/AccountOptions.tsx:
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/BackupChars.tsx:
  - (2, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/BackupSeeds.tsx:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/ColumnGrid.tsx:
  - (2, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/SignUpChars.tsx:
  - (4, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/SignUpSeeds.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
Issues in app/client/src/utils/constants.ts:
  - (7, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
Issues in app/client/src/utils/interfaces.ts:
  - (23, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
Issues in app/server/managers/wasmManager.js:
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in mobile/App.tsx:
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
Issues in mobile/src/navigation/RootNavigation.tsx:
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
