### ISSUE TITLE
Issue-chore: Update UI Components

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#646]
Automated Review Comments
Issues in app/client/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in app/client/src/components/commons/Input.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in app/client/src/components/commons/Text.tsx:
  - (1, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/Assets.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/Summary.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/SummaryItem.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/SwitchButton.tsx:
  - (2, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/TokenComponent.tsx:
  - (2, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/Tokens.tsx:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/modal/Token.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/modal/TokenFormsModal.tsx:
  - (27, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/modal/TokenModal.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/select/TokenSelect.tsx:
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/InnerContainer.tsx:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/Navbar.tsx:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/Sidebar.tsx:
  - (32, 'Hardcoded string found')
Issues in app/client/src/contexts/AuthContext.tsx:
  - (4, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (140, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (221, 'Line exceeds 80 characters')
  - (229, 'Line exceeds 80 characters')
  - (240, 'Line exceeds 80 characters')
Issues in app/client/src/index.css:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
Issues in app/client/src/pages/Accounts/Accounts.tsx:
  - (14, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (174, 'Hardcoded string found')
  - (182, 'Line exceeds 80 characters')
  - (182, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (215, 'Line exceeds 80 characters')
  - (215, 'Hardcoded string found')
Issues in app/client/src/pages/Dashboard.tsx:
  - (5, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Settings.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/AccountOptions.tsx:
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/ColumnGrid.tsx:
  - (2, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/SignUpChars.tsx:
  - (4, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/SignUpSeeds.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
Issues in app/client/src/utils/constants.ts:
  - (7, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
Issues in app/client/src/utils/interfaces.ts:
  - (33, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
