### ISSUE TITLE
Issue-Updated wasm

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#650]
Automated Review Comments
Issues in app/client/src/components/commons/Input.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in app/client/src/components/commons/Text.tsx:
  - (1, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/Assets.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/Summary.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/SummaryItem.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/SwitchButton.tsx:
  - (2, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/Tokens.tsx:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/modal/Token.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (67, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/modal/TokenFormsModal.tsx:
  - (27, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/modal/TokenModal.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/select/TokenSelect.tsx:
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/InnerContainer.tsx:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/Navbar.tsx:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
Issues in app/client/src/components/layout/Sidebar.tsx:
  - (28, 'Hardcoded string found')
Issues in app/client/src/contexts/AuthContext.tsx:
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (151, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (181, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (197, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (208, 'Hardcoded string found')
Issues in app/client/src/index.css:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
Issues in app/client/src/pages/Accounts/Accounts.tsx:
  - (12, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (95, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (115, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
Issues in app/client/src/pages/Dashboard.tsx:
  - (6, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Settings.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/ColumnGrid.tsx:
  - (2, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/SignUpChars.tsx:
  - (1, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/SignUpSeeds.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
Issues in app/client/src/utils/constants.ts:
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in app/client/src/utils/interfaces.ts:
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (3, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in app/server/managers/wasmManager.js:
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in mobile/App.tsx:
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (37, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
