### ISSUE TITLE
Issue-Configure macos

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#652]
Automated Review Comments
Issues in app/server/main.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
Issues in app/server/managers/wasmManager.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
