### ISSUE TITLE
Issue-feat: Add new restore page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#661]
Automated Review Comments
Issues in .github/workflows/pr-main.yml:
  - (2, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
Issues in app/client/src/components/commons/Input.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in app/client/src/components/commons/Text.tsx:
  - (1, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/Assets.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/Summary.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/SummaryItem.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/SwitchButton.tsx:
  - (2, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/Tokens.tsx:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/modal/Token.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/modal/TokenFormsModal.tsx:
  - (27, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (95, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/modal/TokenModal.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/select/TokenSelect.tsx:
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/InnerContainer.tsx:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/Navbar.tsx:
  - (2, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/Sidebar.tsx:
  - (28, 'Hardcoded string found')
Issues in app/client/src/contexts/AuthContext.tsx:
  - (4, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (187, 'Line exceeds 80 characters')
  - (194, 'Line exceeds 80 characters')
  - (200, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (212, 'Hardcoded string found')
Issues in app/client/src/index.css:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
Issues in app/client/src/pages/Accounts/Accounts.tsx:
  - (12, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
Issues in app/client/src/pages/Dashboard.tsx:
  - (5, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Settings.tsx:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/ColumnGrid.tsx:
  - (2, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/SignUpChars.tsx:
  - (1, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/SignUpSeeds.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
Issues in app/client/src/utils/constants.ts:
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in app/client/src/utils/interfaces.ts:
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (3, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in app/server/main.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
