### ISSUE TITLE
Issue-feat: add New Create Page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#665]
Automated Review Comments
Issues in mobile/src/navigation/RootNavigation.tsx:
  - (1, 'Line exceeds 80 characters')
Issues in mobile/src/screens/Setup/Create/index.tsx:
  - (2, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Restore/index.tsx:
  - (2, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/WalletSetup.tsx:
  - (2, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
