### ISSUE TITLE
Issue-Migrate basic logic to React version

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#67]
Automated Review Comments
Issues in app/client/index.html:
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in app/client/package-lock.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (114, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Line exceeds 80 characters')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Line exceeds 80 characters')
  - (175, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Line exceeds 80 characters')
  - (187, 'Hardcoded string found')
  - (189, 'Line exceeds 80 characters')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Line exceeds 80 characters')
  - (194, 'Hardcoded string found')
  - (195, 'Line exceeds 80 characters')
  - (195, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Line exceeds 80 characters')
  - (205, 'Hardcoded string found')
  - (207, 'Line exceeds 80 characters')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (213, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Line exceeds 80 characters')
  - (225, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (231, 'Line exceeds 80 characters')
  - (231, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (236, 'Line exceeds 80 characters')
  - (236, 'Hardcoded string found')
  - (237, 'Line exceeds 80 characters')
  - (237, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (246, 'Line exceeds 80 characters')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (251, 'Line exceeds 80 characters')
  - (251, 'Hardcoded string found')
  - (252, 'Line exceeds 80 characters')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (263, 'Hardcoded string found')
  - (264, 'Line exceeds 80 characters')
  - (264, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (277, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (283, 'Line exceeds 80 characters')
  - (283, 'Hardcoded string found')
  - (284, 'Line exceeds 80 characters')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (292, 'Line exceeds 80 characters')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (306, 'Line exceeds 80 characters')
  - (306, 'Hardcoded string found')
  - (307, 'Line exceeds 80 characters')
  - (307, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (316, 'Line exceeds 80 characters')
  - (316, 'Hardcoded string found')
  - (317, 'Line exceeds 80 characters')
  - (317, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (330, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (336, 'Line exceeds 80 characters')
  - (336, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (338, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Line exceeds 80 characters')
  - (356, 'Hardcoded string found')
  - (357, 'Line exceeds 80 characters')
  - (357, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (366, 'Line exceeds 80 characters')
  - (366, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (373, 'Line exceeds 80 characters')
  - (373, 'Hardcoded string found')
  - (375, 'Line exceeds 80 characters')
  - (375, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (380, 'Line exceeds 80 characters')
  - (380, 'Hardcoded string found')
  - (381, 'Line exceeds 80 characters')
  - (381, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (400, 'Line exceeds 80 characters')
  - (400, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (402, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (412, 'Line exceeds 80 characters')
  - (412, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (420, 'Line exceeds 80 characters')
  - (420, 'Hardcoded string found')
  - (421, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (425, 'Line exceeds 80 characters')
  - (425, 'Hardcoded string found')
  - (427, 'Line exceeds 80 characters')
  - (427, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
  - (432, 'Line exceeds 80 characters')
  - (432, 'Hardcoded string found')
  - (433, 'Line exceeds 80 characters')
  - (433, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (435, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (444, 'Line exceeds 80 characters')
  - (444, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (451, 'Line exceeds 80 characters')
  - (451, 'Hardcoded string found')
  - (452, 'Line exceeds 80 characters')
  - (452, 'Hardcoded string found')
  - (455, 'Hardcoded string found')
  - (456, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (463, 'Hardcoded string found')
  - (464, 'Line exceeds 80 characters')
  - (464, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (466, 'Hardcoded string found')
  - (470, 'Hardcoded string found')
  - (471, 'Line exceeds 80 characters')
  - (471, 'Hardcoded string found')
  - (472, 'Line exceeds 80 characters')
  - (472, 'Hardcoded string found')
  - (473, 'Hardcoded string found')
  - (476, 'Hardcoded string found')
  - (477, 'Hardcoded string found')
  - (481, 'Hardcoded string found')
  - (482, 'Hardcoded string found')
  - (485, 'Hardcoded string found')
  - (486, 'Hardcoded string found')
  - (487, 'Line exceeds 80 characters')
  - (487, 'Hardcoded string found')
  - (488, 'Hardcoded string found')
  - (489, 'Line exceeds 80 characters')
  - (489, 'Hardcoded string found')
  - (492, 'Hardcoded string found')
  - (494, 'Line exceeds 80 characters')
  - (494, 'Hardcoded string found')
  - (495, 'Hardcoded string found')
  - (498, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (500, 'Line exceeds 80 characters')
  - (500, 'Hardcoded string found')
  - (503, 'Hardcoded string found')
  - (504, 'Line exceeds 80 characters')
  - (504, 'Hardcoded string found')
  - (505, 'Line exceeds 80 characters')
  - (505, 'Hardcoded string found')
  - (506, 'Hardcoded string found')
  - (513, 'Hardcoded string found')
  - (514, 'Line exceeds 80 characters')
  - (514, 'Hardcoded string found')
  - (515, 'Line exceeds 80 characters')
  - (515, 'Hardcoded string found')
  - (516, 'Hardcoded string found')
  - (519, 'Hardcoded string found')
  - (520, 'Line exceeds 80 characters')
  - (520, 'Hardcoded string found')
  - (521, 'Line exceeds 80 characters')
  - (521, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (523, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (528, 'Hardcoded string found')
  - (529, 'Hardcoded string found')
  - (531, 'Hardcoded string found')
  - (535, 'Hardcoded string found')
  - (536, 'Line exceeds 80 characters')
  - (536, 'Hardcoded string found')
  - (537, 'Line exceeds 80 characters')
  - (537, 'Hardcoded string found')
  - (540, 'Hardcoded string found')
  - (541, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (547, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (549, 'Line exceeds 80 characters')
  - (549, 'Hardcoded string found')
  - (550, 'Hardcoded string found')
  - (551, 'Hardcoded string found')
  - (552, 'Hardcoded string found')
  - (554, 'Hardcoded string found')
  - (555, 'Hardcoded string found')
  - (559, 'Hardcoded string found')
  - (560, 'Line exceeds 80 characters')
  - (560, 'Hardcoded string found')
  - (566, 'Hardcoded string found')
  - (567, 'Hardcoded string found')
  - (568, 'Line exceeds 80 characters')
  - (568, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (570, 'Hardcoded string found')
  - (571, 'Hardcoded string found')
  - (572, 'Hardcoded string found')
  - (575, 'Hardcoded string found')
  - (576, 'Hardcoded string found')
  - (578, 'Hardcoded string found')
  - (579, 'Hardcoded string found')
  - (583, 'Hardcoded string found')
  - (584, 'Line exceeds 80 characters')
  - (584, 'Hardcoded string found')
  - (586, 'Hardcoded string found')
  - (590, 'Hardcoded string found')
  - (591, 'Line exceeds 80 characters')
  - (591, 'Hardcoded string found')
  - (592, 'Line exceeds 80 characters')
  - (592, 'Hardcoded string found')
  - (593, 'Hardcoded string found')
  - (595, 'Hardcoded string found')
  - (599, 'Hardcoded string found')
  - (600, 'Hardcoded string found')
  - (604, 'Hardcoded string found')
  - (605, 'Line exceeds 80 characters')
  - (605, 'Hardcoded string found')
  - (606, 'Line exceeds 80 characters')
  - (606, 'Hardcoded string found')
  - (607, 'Hardcoded string found')
  - (609, 'Hardcoded string found')
  - (611, 'Hardcoded string found')
  - (612, 'Hardcoded string found')
  - (616, 'Hardcoded string found')
  - (617, 'Line exceeds 80 characters')
  - (617, 'Hardcoded string found')
  - (619, 'Hardcoded string found')
  - (623, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (625, 'Line exceeds 80 characters')
  - (625, 'Hardcoded string found')
  - (628, 'Hardcoded string found')
  - (629, 'Line exceeds 80 characters')
  - (629, 'Hardcoded string found')
  - (631, 'Hardcoded string found')
  - (635, 'Hardcoded string found')
  - (636, 'Line exceeds 80 characters')
  - (636, 'Hardcoded string found')
  - (637, 'Line exceeds 80 characters')
  - (637, 'Hardcoded string found')
  - (638, 'Hardcoded string found')
  - (643, 'Hardcoded string found')
  - (644, 'Line exceeds 80 characters')
  - (644, 'Hardcoded string found')
  - (646, 'Hardcoded string found')
  - (650, 'Hardcoded string found')
  - (651, 'Line exceeds 80 characters')
  - (651, 'Hardcoded string found')
  - (652, 'Line exceeds 80 characters')
  - (652, 'Hardcoded string found')
  - (655, 'Hardcoded string found')
  - (656, 'Line exceeds 80 characters')
  - (656, 'Hardcoded string found')
  - (658, 'Hardcoded string found')
  - (662, 'Hardcoded string found')
  - (663, 'Line exceeds 80 characters')
  - (663, 'Hardcoded string found')
  - (664, 'Line exceeds 80 characters')
  - (664, 'Hardcoded string found')
  - (665, 'Hardcoded string found')
  - (666, 'Hardcoded string found')
  - (669, 'Hardcoded string found')
  - (670, 'Hardcoded string found')
  - (674, 'Hardcoded string found')
  - (675, 'Hardcoded string found')
  - (681, 'Hardcoded string found')
  - (682, 'Line exceeds 80 characters')
  - (682, 'Hardcoded string found')
  - (683, 'Line exceeds 80 characters')
  - (683, 'Hardcoded string found')
  - (684, 'Hardcoded string found')
  - (685, 'Hardcoded string found')
  - (686, 'Hardcoded string found')
  - (690, 'Hardcoded string found')
  - (692, 'Hardcoded string found')
  - (693, 'Hardcoded string found')
  - (697, 'Hardcoded string found')
  - (698, 'Hardcoded string found')
  - (699, 'Line exceeds 80 characters')
  - (699, 'Hardcoded string found')
  - (700, 'Hardcoded string found')
  - (701, 'Hardcoded string found')
  - (705, 'Hardcoded string found')
  - (706, 'Hardcoded string found')
  - (707, 'Line exceeds 80 characters')
  - (707, 'Hardcoded string found')
  - (710, 'Hardcoded string found')
  - (711, 'Hardcoded string found')
  - (713, 'Line exceeds 80 characters')
  - (713, 'Hardcoded string found')
  - (714, 'Hardcoded string found')
  - (717, 'Hardcoded string found')
  - (718, 'Hardcoded string found')
  - (719, 'Line exceeds 80 characters')
  - (719, 'Hardcoded string found')
  - (720, 'Hardcoded string found')
  - (721, 'Hardcoded string found')
  - (723, 'Hardcoded string found')
  - (724, 'Hardcoded string found')
  - (727, 'Hardcoded string found')
  - (728, 'Hardcoded string found')
  - (729, 'Hardcoded string found')
  - (732, 'Hardcoded string found')
  - (737, 'Hardcoded string found')
  - (738, 'Line exceeds 80 characters')
  - (738, 'Hardcoded string found')
  - (739, 'Line exceeds 80 characters')
  - (739, 'Hardcoded string found')
  - (740, 'Hardcoded string found')
  - (741, 'Hardcoded string found')
  - (745, 'Hardcoded string found')
  - (746, 'Hardcoded string found')
  - (747, 'Line exceeds 80 characters')
  - (747, 'Hardcoded string found')
  - (748, 'Hardcoded string found')
  - (749, 'Hardcoded string found')
  - (753, 'Hardcoded string found')
  - (754, 'Hardcoded string found')
Issues in app/client/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
Issues in app/client/src/App.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
Issues in app/client/src/assets/css/style.scss:
  - (5, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
Issues in app/client/src/main.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in app/server/controllers/socketController.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in app/server/managers/wasmManager.js:
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
Issues in app/server/package-lock.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (145, 'Line exceeds 80 characters')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Line exceeds 80 characters')
  - (152, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Line exceeds 80 characters')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (176, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (186, 'Line exceeds 80 characters')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Line exceeds 80 characters')
  - (202, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (206, 'Line exceeds 80 characters')
  - (206, 'Hardcoded string found')
  - (207, 'Line exceeds 80 characters')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (219, 'Line exceeds 80 characters')
  - (219, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (235, 'Line exceeds 80 characters')
  - (235, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (240, 'Line exceeds 80 characters')
  - (240, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (256, 'Line exceeds 80 characters')
  - (256, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (263, 'Line exceeds 80 characters')
  - (263, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (267, 'Line exceeds 80 characters')
  - (267, 'Hardcoded string found')
  - (268, 'Line exceeds 80 characters')
  - (268, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Line exceeds 80 characters')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
Issues in app/server/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in app/server/routes.js:
  - (2, 'Hardcoded string found')
Issues in app/server/server.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
Issues in app/server/utils/constants.js:
  - (2, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.

**Comment by satomichru** [comment]
I got it.
