### ISSUE TITLE
Issue-Updated signup ux

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#671]
Automated Review Comments
Issues in app/client/src/pages/Login/Login.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/SignUp.tsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
