### ISSUE TITLE
Issue-Backup ux

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#673]
Automated Review Comments
Issues in app/client/src/pages/SignUp/SignUpChars.tsx:
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
