### ISSUE TITLE
Issue-Added confirm flow and update ux

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#677]
Automated Review Comments
Issues in app/client/src/pages/SignUp/BackupSeeds.tsx:
  - (6, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/ColumnGrid.tsx:
  - (5, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
