### ISSUE TITLE
Issue-Merge pull request #69 from RealWorld777/staging

Working on new UI - Splash, Setup, Create, Restore, Reminder

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#679]
Automated Review Comments
Issues in app/client/src/components/commons/Button.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
Issues in app/client/src/contexts/AuthContext.tsx:
  - (15, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in app/client/src/pages/Login/Login.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/BackupChars.tsx:
  - (6, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/BackupSeeds.tsx:
  - (6, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/ColumnGrid.tsx:
  - (5, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/SignUp.tsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/SignUpChars.tsx:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/SignUpSeeds.tsx:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
Issues in app/server/controllers/socketController.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
Issues in mobile/App.tsx:
  - (12, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
Issues in mobile/package-lock.json:
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in mobile/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in mobile/src/components/UI/Input.tsx:
  - (1, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in mobile/src/navigation/RootNavigation.tsx:
  - (1, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/index.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/WalletSetup.tsx:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in mobile/src/utils/utils.ts:
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
