### ISSUE TITLE
Issue-Backup seeds

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#681]
Automated Review Comments
Issues in app/client/src/components/commons/Button.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
Issues in app/client/src/contexts/AuthContext.tsx:
  - (15, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in app/client/src/pages/Login/Login.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/BackupChars.tsx:
  - (6, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/BackupSeeds.tsx:
  - (6, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/ColumnGrid.tsx:
  - (5, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/SignUp.tsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/SignUpChars.tsx:
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/SignUpSeeds.tsx:
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in app/server/controllers/socketController.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
Issues in mobile/App.tsx:
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
Issues in mobile/package-lock.json:
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
Issues in mobile/package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in mobile/src/navigation/RootNavigation.tsx:
  - (1, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
