### ISSUE TITLE
Issue-Recover, accounts, balances

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#689]
Automated Review Comments
Issues in app/client/src/components/dashboard/Summary.tsx:
  - (16, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
Issues in app/client/src/components/layout/Navbar.tsx:
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
Issues in app/client/src/contexts/AuthContext.tsx:
  - (52, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Accounts/Accounts.tsx:
  - (2, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
Issues in app/client/src/pages/Login/Login.tsx:
  - (2, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/AccountOptions.tsx:
  - (21, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/BackupChars.tsx:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/BackupSeeds.tsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
