### ISSUE TITLE
Issue-feat: add display seed page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#697]
Automated Review Comments
Issues in app/client/package-lock.json:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Line exceeds 80 characters')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (145, 'Line exceeds 80 characters')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Line exceeds 80 characters')
  - (161, 'Hardcoded string found')
  - (162, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (166, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
  - (178, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Line exceeds 80 characters')
  - (182, 'Hardcoded string found')
  - (183, 'Line exceeds 80 characters')
  - (183, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (197, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Line exceeds 80 characters')
  - (200, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Line exceeds 80 characters')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (213, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (218, 'Line exceeds 80 characters')
  - (218, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (225, 'Line exceeds 80 characters')
  - (225, 'Hardcoded string found')
  - (226, 'Line exceeds 80 characters')
  - (226, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (235, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (238, 'Line exceeds 80 characters')
  - (238, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (244, 'Line exceeds 80 characters')
  - (244, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (248, 'Line exceeds 80 characters')
  - (248, 'Hardcoded string found')
  - (250, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (255, 'Line exceeds 80 characters')
  - (255, 'Hardcoded string found')
  - (256, 'Line exceeds 80 characters')
  - (256, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
Issues in app/client/package.json:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in app/client/src/components/commons/Button.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
Issues in app/client/src/components/commons/Input.tsx:
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
Issues in app/client/src/components/commons/Select.tsx:
  - (4, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/Summary.tsx:
  - (20, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
Issues in app/client/src/components/layout/InnerContainer.tsx:
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/Navbar.tsx:
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
Issues in app/client/src/contexts/AuthContext.tsx:
  - (52, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Accounts/Accounts.tsx:
  - (2, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
Issues in app/client/src/pages/Login/Login.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/AccountOptions.tsx:
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/BackupChars.tsx:
  - (8, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/BackupSeeds.tsx:
  - (9, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/ColumnGrid.tsx:
  - (5, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/SignUp.tsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (103, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
Issues in app/client/src/pages/SignUp/SignUpChars.tsx:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
Issues in app/client/src/pages/SignUp/SignUpSeeds.tsx:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
Issues in app/client/src/routes/AppRoutes.tsx:
  - (1, 'Line exceeds 80 characters')
Issues in app/client/src/utils/constants.ts:
  - (3, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
Issues in app/server/controllers/socketController.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
Issues in mobile/src/components/UI/Input.tsx:
  - (1, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in mobile/src/navigation/RootNavigation.tsx:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/Confirm.tsx:
  - (11, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/Reminder.tsx:
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/index.tsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/WalletSetup.tsx:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in mobile/src/utils/utils.ts:
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
