### ISSUE TITLE
Issue-feat: add seed confirm page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#699]
Automated Review Comments
Issues in mobile/src/components/UI/PageButton.tsx:
  - (3, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/Confirm.tsx:
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/CreatePassword.tsx:
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/Reminder.tsx:
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Restore/index.tsx:
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/WalletSetup.tsx:
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
Issues in mobile/src/screens/Splash/Splash.tsx:
  - (1, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
