### ISSUE TITLE
Issue-Send feature

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#707]
Automated Review Comments
Issues in app/client/src/components/dashboard/Tokens.tsx:
  - (5, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/modal/TokenFormsModal.tsx:
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
Issues in app/client/src/components/dashboard/modal/TokenModal.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (126, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (151, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (155, 'Line exceeds 80 characters')
  - (162, 'Hardcoded string found')
  - (164, 'Line exceeds 80 characters')
  - (171, 'Line exceeds 80 characters')
  - (171, 'Hardcoded string found')
  - (173, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
