### ISSUE TITLE
Issue-Update cli socket

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#709]
Automated Review Comments
Issues in app/client/src/components/dashboard/modal/TokenFormsModal.tsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in app/client/src/utils/constants.ts:
  - (7, 'Hardcoded string found')
Issues in app/server/controllers/socketController.js:
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
