### ISSUE TITLE
Issue-Integrate theme provider

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#71]
Automated Review Comments
Issues in app/client/src/App.tsx:
  - (3, 'Hardcoded string found')
Issues in app/client/src/components/theme/ThemeToggle.tsx:
  - (2, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in app/client/src/context/ThemeContext.tsx:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Dashboard.tsx:
  - (2, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
Issues in app/client/src/utils/svgs.tsx:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
Issues in app/client/tailwind.config.js:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
