### ISSUE TITLE
Issue-update setting ui and totalbalance

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#715]
Automated Review Comments
Issues in app/client/src/components/layout/Navbar.tsx:
  - (1, 'Hardcoded string found')
Issues in app/client/src/contexts/AuthContext.tsx:
  - (21, 'Hardcoded string found')
Issues in app/client/src/enums/SettingsItems.ts:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in app/client/src/pages/Settings/InnerSettings.tsx:
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
Issues in app/client/src/utils/constants.ts:
  - (6, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
Issues in app/server/controllers/mainController.js:
  - (3, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
