### ISSUE TITLE
Issue-refactor: refactoring create logic, add SeedType Page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#723]
Automated Review Comments
Issues in mobile/src/context/AuthContext.tsx:
  - (21, 'Line exceeds 80 characters')
Issues in mobile/src/screens/Setup/Create/Confirm.tsx:
  - (8, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (164, 'Line exceeds 80 characters')
Issues in mobile/src/screens/Setup/Create/CreatePassword.tsx:
  - (9, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/Reminder.tsx:
  - (1, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/SeedType.tsx:
  - (2, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/index.tsx:
  - (2, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in mobile/tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
