### ISSUE TITLE
Issue-feat: add localization with chinese

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#727]
Automated Review Comments
Issues in mobile/package-lock.json:
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
Issues in mobile/src/navigation/RootNavigation.tsx:
  - (2, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/Confirm.tsx:
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/CreatePassword.tsx:
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/Reminder.tsx:
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/SeedType.tsx:
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/index.tsx:
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Restore/index.tsx:
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/WalletSetup.tsx:
  - (10, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
Issues in mobile/src/screens/Splash/Splash.tsx:
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in mobile/src/utils/locales/languages.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (137, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
