### ISSUE TITLE
Issue-feat: add login page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#729]
Automated Review Comments
Issues in mobile/App.tsx:
  - (7, 'Hardcoded string found')
Issues in mobile/src/screens/Login/index.tsx:
  - (2, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (62, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
Issues in mobile/src/screens/Settings/index.tsx:
  - (3, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/SeedType.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/WalletSetup.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in mobile/src/screens/Splash/Splash.tsx:
  - (2, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
Issues in mobile/src/screens/Swap/index.tsx:
  - (3, 'Hardcoded string found')
Issues in mobile/src/utils/locales/languages.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
