### ISSUE TITLE
Issue-Update background

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#73]
Automated Review Comments
Issues in app/client/src/App.tsx:
  - (2, 'Hardcoded string found')
Issues in app/client/src/context/ThemeContext.tsx:
  - (4, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Dashboard.tsx:
  - (2, 'Hardcoded string found')
Issues in app/client/src/pages/Login.tsx:
  - (2, 'Hardcoded string found')
Issues in app/client/src/routes/AppRoutes.tsx:
  - (2, 'Hardcoded string found')
Issues in app/client/src/utils/svgs.tsx:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
