### ISSUE TITLE
Issue-Display orders

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#733]
Automated Review Comments
Issues in app/client/src/components/commons/Select.tsx:
  - (2, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in app/client/src/components/dashboard/select/TokenSelect.tsx:
  - (2, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
Issues in app/client/src/components/layout/Navbar.tsx:
  - (1, 'Hardcoded string found')
Issues in app/client/src/contexts/AuthContext.tsx:
  - (3, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
Issues in app/client/src/enums/SettingsItems.ts:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in app/client/src/pages/Settings/InnerSettings.tsx:
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Trading/Trading.tsx:
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (112, 'Line exceeds 80 characters')
  - (112, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (114, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (115, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (121, 'Line exceeds 80 characters')
  - (121, 'Hardcoded string found')
  - (122, 'Line exceeds 80 characters')
  - (122, 'Hardcoded string found')
  - (123, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (124, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (129, 'Line exceeds 80 characters')
  - (131, 'Line exceeds 80 characters')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (133, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (138, 'Hardcoded string found')
  - (139, 'Line exceeds 80 characters')
Issues in app/client/src/utils/constants.ts:
  - (6, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
Issues in app/client/src/utils/interfaces.ts:
  - (5, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
Issues in app/client/src/utils/mock.ts:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (264, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (359, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (399, 'Hardcoded string found')
  - (404, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (419, 'Hardcoded string found')
  - (424, 'Hardcoded string found')
  - (429, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (449, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (464, 'Hardcoded string found')
  - (469, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (489, 'Hardcoded string found')
  - (494, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (504, 'Hardcoded string found')
  - (509, 'Hardcoded string found')
  - (514, 'Hardcoded string found')
  - (519, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (529, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (539, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (554, 'Hardcoded string found')
  - (559, 'Hardcoded string found')
  - (564, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (574, 'Hardcoded string found')
  - (579, 'Hardcoded string found')
  - (584, 'Hardcoded string found')
  - (589, 'Hardcoded string found')
  - (594, 'Hardcoded string found')
  - (599, 'Hardcoded string found')
  - (604, 'Hardcoded string found')
  - (609, 'Hardcoded string found')
  - (614, 'Hardcoded string found')
  - (619, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (629, 'Hardcoded string found')
  - (634, 'Hardcoded string found')
  - (639, 'Hardcoded string found')
  - (644, 'Hardcoded string found')
  - (649, 'Hardcoded string found')
  - (654, 'Hardcoded string found')
  - (659, 'Hardcoded string found')
  - (664, 'Hardcoded string found')
  - (669, 'Hardcoded string found')
  - (674, 'Hardcoded string found')
  - (679, 'Hardcoded string found')
  - (684, 'Hardcoded string found')
  - (689, 'Hardcoded string found')
  - (694, 'Hardcoded string found')
  - (699, 'Hardcoded string found')
  - (704, 'Hardcoded string found')
  - (709, 'Hardcoded string found')
  - (714, 'Hardcoded string found')
  - (719, 'Hardcoded string found')
  - (724, 'Hardcoded string found')
  - (729, 'Hardcoded string found')
  - (734, 'Hardcoded string found')
  - (739, 'Hardcoded string found')
  - (744, 'Hardcoded string found')
  - (749, 'Hardcoded string found')
  - (754, 'Hardcoded string found')
  - (759, 'Hardcoded string found')
  - (764, 'Hardcoded string found')
  - (769, 'Hardcoded string found')
  - (774, 'Hardcoded string found')
  - (779, 'Hardcoded string found')
  - (784, 'Hardcoded string found')
  - (789, 'Hardcoded string found')
  - (794, 'Hardcoded string found')
  - (799, 'Hardcoded string found')
  - (804, 'Hardcoded string found')
  - (809, 'Hardcoded string found')
  - (814, 'Hardcoded string found')
  - (819, 'Hardcoded string found')
  - (824, 'Hardcoded string found')
  - (829, 'Hardcoded string found')
  - (834, 'Hardcoded string found')
  - (839, 'Hardcoded string found')
  - (844, 'Hardcoded string found')
  - (849, 'Hardcoded string found')
  - (854, 'Hardcoded string found')
  - (859, 'Hardcoded string found')
  - (864, 'Hardcoded string found')
  - (869, 'Hardcoded string found')
  - (874, 'Hardcoded string found')
  - (879, 'Hardcoded string found')
  - (884, 'Hardcoded string found')
  - (889, 'Hardcoded string found')
  - (894, 'Hardcoded string found')
  - (899, 'Hardcoded string found')
  - (904, 'Hardcoded string found')
  - (909, 'Hardcoded string found')
  - (914, 'Hardcoded string found')
  - (919, 'Hardcoded string found')
  - (924, 'Hardcoded string found')
  - (929, 'Hardcoded string found')
  - (934, 'Hardcoded string found')
  - (939, 'Hardcoded string found')
  - (944, 'Hardcoded string found')
  - (949, 'Hardcoded string found')
  - (954, 'Hardcoded string found')
  - (959, 'Hardcoded string found')
  - (964, 'Hardcoded string found')
  - (969, 'Hardcoded string found')
  - (974, 'Hardcoded string found')
  - (979, 'Hardcoded string found')
  - (984, 'Hardcoded string found')
  - (989, 'Hardcoded string found')
  - (994, 'Hardcoded string found')
  - (999, 'Hardcoded string found')
  - (1004, 'Hardcoded string found')
  - (1009, 'Hardcoded string found')
  - (1014, 'Hardcoded string found')
  - (1019, 'Hardcoded string found')
  - (1024, 'Hardcoded string found')
  - (1029, 'Hardcoded string found')
  - (1034, 'Hardcoded string found')
  - (1039, 'Hardcoded string found')
  - (1044, 'Hardcoded string found')
  - (1049, 'Hardcoded string found')
  - (1054, 'Hardcoded string found')
  - (1059, 'Hardcoded string found')
  - (1064, 'Hardcoded string found')
  - (1069, 'Hardcoded string found')
  - (1074, 'Hardcoded string found')
  - (1079, 'Hardcoded string found')
  - (1084, 'Hardcoded string found')
  - (1089, 'Hardcoded string found')
  - (1094, 'Hardcoded string found')
  - (1099, 'Hardcoded string found')
  - (1104, 'Hardcoded string found')
  - (1109, 'Hardcoded string found')
  - (1114, 'Hardcoded string found')
  - (1119, 'Hardcoded string found')
  - (1124, 'Hardcoded string found')
  - (1129, 'Hardcoded string found')
  - (1134, 'Hardcoded string found')
  - (1139, 'Hardcoded string found')
  - (1144, 'Hardcoded string found')
  - (1149, 'Hardcoded string found')
  - (1154, 'Hardcoded string found')
  - (1159, 'Hardcoded string found')
  - (1164, 'Hardcoded string found')
  - (1169, 'Hardcoded string found')
  - (1174, 'Hardcoded string found')
  - (1179, 'Hardcoded string found')
  - (1184, 'Hardcoded string found')
  - (1189, 'Hardcoded string found')
  - (1194, 'Hardcoded string found')
  - (1199, 'Hardcoded string found')
  - (1204, 'Hardcoded string found')
  - (1209, 'Hardcoded string found')
  - (1214, 'Hardcoded string found')
  - (1219, 'Hardcoded string found')
  - (1224, 'Hardcoded string found')
  - (1229, 'Hardcoded string found')
  - (1234, 'Hardcoded string found')
  - (1239, 'Hardcoded string found')
  - (1244, 'Hardcoded string found')
  - (1249, 'Hardcoded string found')
  - (1254, 'Hardcoded string found')
  - (1259, 'Hardcoded string found')
  - (1264, 'Hardcoded string found')
  - (1269, 'Hardcoded string found')
  - (1274, 'Hardcoded string found')
  - (1279, 'Hardcoded string found')
  - (1284, 'Hardcoded string found')
  - (1289, 'Hardcoded string found')
  - (1291, 'Hardcoded string found')
  - (1296, 'Hardcoded string found')
  - (1301, 'Hardcoded string found')
  - (1306, 'Hardcoded string found')
  - (1311, 'Hardcoded string found')
  - (1316, 'Hardcoded string found')
  - (1321, 'Hardcoded string found')
  - (1326, 'Hardcoded string found')
  - (1331, 'Hardcoded string found')
  - (1336, 'Hardcoded string found')
  - (1341, 'Hardcoded string found')
  - (1346, 'Hardcoded string found')
  - (1351, 'Hardcoded string found')
  - (1356, 'Hardcoded string found')
  - (1361, 'Hardcoded string found')
  - (1366, 'Hardcoded string found')
  - (1371, 'Hardcoded string found')
  - (1376, 'Hardcoded string found')
  - (1381, 'Hardcoded string found')
  - (1386, 'Hardcoded string found')
  - (1391, 'Hardcoded string found')
  - (1396, 'Hardcoded string found')
  - (1401, 'Hardcoded string found')
  - (1406, 'Hardcoded string found')
  - (1411, 'Hardcoded string found')
  - (1416, 'Hardcoded string found')
  - (1421, 'Hardcoded string found')
  - (1426, 'Hardcoded string found')
  - (1431, 'Hardcoded string found')
  - (1436, 'Hardcoded string found')
  - (1441, 'Hardcoded string found')
  - (1446, 'Hardcoded string found')
  - (1451, 'Hardcoded string found')
  - (1456, 'Hardcoded string found')
  - (1461, 'Hardcoded string found')
  - (1466, 'Hardcoded string found')
  - (1471, 'Hardcoded string found')
  - (1476, 'Hardcoded string found')
  - (1481, 'Hardcoded string found')
  - (1486, 'Hardcoded string found')
  - (1491, 'Hardcoded string found')
  - (1496, 'Hardcoded string found')
  - (1501, 'Hardcoded string found')
  - (1506, 'Hardcoded string found')
  - (1511, 'Hardcoded string found')
  - (1516, 'Hardcoded string found')
  - (1521, 'Hardcoded string found')
  - (1526, 'Hardcoded string found')
  - (1531, 'Hardcoded string found')
  - (1536, 'Hardcoded string found')
  - (1541, 'Hardcoded string found')
  - (1546, 'Hardcoded string found')
  - (1551, 'Hardcoded string found')
  - (1556, 'Hardcoded string found')
  - (1561, 'Hardcoded string found')
  - (1566, 'Hardcoded string found')
  - (1571, 'Hardcoded string found')
  - (1576, 'Hardcoded string found')
  - (1581, 'Hardcoded string found')
  - (1586, 'Hardcoded string found')
  - (1591, 'Hardcoded string found')
  - (1596, 'Hardcoded string found')
  - (1601, 'Hardcoded string found')
  - (1606, 'Hardcoded string found')
  - (1611, 'Hardcoded string found')
  - (1616, 'Hardcoded string found')
  - (1621, 'Hardcoded string found')
  - (1626, 'Hardcoded string found')
  - (1631, 'Hardcoded string found')
  - (1636, 'Hardcoded string found')
  - (1641, 'Hardcoded string found')
  - (1646, 'Hardcoded string found')
  - (1651, 'Hardcoded string found')
  - (1656, 'Hardcoded string found')
  - (1661, 'Hardcoded string found')
  - (1666, 'Hardcoded string found')
  - (1671, 'Hardcoded string found')
  - (1676, 'Hardcoded string found')
  - (1681, 'Hardcoded string found')
  - (1686, 'Hardcoded string found')
  - (1691, 'Hardcoded string found')
  - (1696, 'Hardcoded string found')
  - (1701, 'Hardcoded string found')
  - (1706, 'Hardcoded string found')
  - (1711, 'Hardcoded string found')
  - (1716, 'Hardcoded string found')
  - (1721, 'Hardcoded string found')
  - (1726, 'Hardcoded string found')
  - (1731, 'Hardcoded string found')
  - (1736, 'Hardcoded string found')
  - (1741, 'Hardcoded string found')
  - (1746, 'Hardcoded string found')
  - (1751, 'Hardcoded string found')
  - (1756, 'Hardcoded string found')
  - (1761, 'Hardcoded string found')
  - (1766, 'Hardcoded string found')
  - (1771, 'Hardcoded string found')
  - (1776, 'Hardcoded string found')
  - (1781, 'Hardcoded string found')
  - (1786, 'Hardcoded string found')
  - (1791, 'Hardcoded string found')
  - (1796, 'Hardcoded string found')
  - (1801, 'Hardcoded string found')
  - (1806, 'Hardcoded string found')
  - (1811, 'Hardcoded string found')
  - (1816, 'Hardcoded string found')
  - (1821, 'Hardcoded string found')
  - (1826, 'Hardcoded string found')
  - (1831, 'Hardcoded string found')
  - (1836, 'Hardcoded string found')
  - (1841, 'Hardcoded string found')
  - (1846, 'Hardcoded string found')
  - (1851, 'Hardcoded string found')
  - (1856, 'Hardcoded string found')
  - (1861, 'Hardcoded string found')
  - (1866, 'Hardcoded string found')
  - (1871, 'Hardcoded string found')
  - (1876, 'Hardcoded string found')
  - (1881, 'Hardcoded string found')
  - (1886, 'Hardcoded string found')
  - (1891, 'Hardcoded string found')
  - (1896, 'Hardcoded string found')
  - (1901, 'Hardcoded string found')
  - (1906, 'Hardcoded string found')
  - (1911, 'Hardcoded string found')
  - (1916, 'Hardcoded string found')
  - (1921, 'Hardcoded string found')
  - (1926, 'Hardcoded string found')
  - (1931, 'Hardcoded string found')
  - (1936, 'Hardcoded string found')
  - (1941, 'Hardcoded string found')
  - (1946, 'Hardcoded string found')
  - (1951, 'Hardcoded string found')
  - (1956, 'Hardcoded string found')
  - (1961, 'Hardcoded string found')
  - (1966, 'Hardcoded string found')
  - (1971, 'Hardcoded string found')
  - (1976, 'Hardcoded string found')
  - (1981, 'Hardcoded string found')
  - (1986, 'Hardcoded string found')
  - (1991, 'Hardcoded string found')
  - (1996, 'Hardcoded string found')
  - (2001, 'Hardcoded string found')
  - (2006, 'Hardcoded string found')
  - (2011, 'Hardcoded string found')
  - (2016, 'Hardcoded string found')
  - (2021, 'Hardcoded string found')
  - (2026, 'Hardcoded string found')
  - (2031, 'Hardcoded string found')
  - (2036, 'Hardcoded string found')
  - (2041, 'Hardcoded string found')
  - (2046, 'Hardcoded string found')
  - (2051, 'Hardcoded string found')
  - (2056, 'Hardcoded string found')
  - (2061, 'Hardcoded string found')
  - (2066, 'Hardcoded string found')
  - (2071, 'Hardcoded string found')
  - (2076, 'Hardcoded string found')
  - (2081, 'Hardcoded string found')
  - (2086, 'Hardcoded string found')
  - (2091, 'Hardcoded string found')
  - (2096, 'Hardcoded string found')
  - (2101, 'Hardcoded string found')
  - (2106, 'Hardcoded string found')
  - (2111, 'Hardcoded string found')
  - (2116, 'Hardcoded string found')
  - (2121, 'Hardcoded string found')
  - (2126, 'Hardcoded string found')
  - (2131, 'Hardcoded string found')
  - (2136, 'Hardcoded string found')
  - (2141, 'Hardcoded string found')
  - (2146, 'Hardcoded string found')
  - (2151, 'Hardcoded string found')
  - (2156, 'Hardcoded string found')
  - (2161, 'Hardcoded string found')
  - (2166, 'Hardcoded string found')
  - (2171, 'Hardcoded string found')
  - (2176, 'Hardcoded string found')
  - (2181, 'Hardcoded string found')
  - (2186, 'Hardcoded string found')
  - (2191, 'Hardcoded string found')
  - (2196, 'Hardcoded string found')
  - (2201, 'Hardcoded string found')
  - (2206, 'Hardcoded string found')
  - (2211, 'Hardcoded string found')
  - (2216, 'Hardcoded string found')
  - (2221, 'Hardcoded string found')
  - (2226, 'Hardcoded string found')
  - (2231, 'Hardcoded string found')
  - (2236, 'Hardcoded string found')
  - (2241, 'Hardcoded string found')
  - (2246, 'Hardcoded string found')
  - (2251, 'Hardcoded string found')
  - (2256, 'Hardcoded string found')
  - (2261, 'Hardcoded string found')
  - (2266, 'Hardcoded string found')
  - (2271, 'Hardcoded string found')
  - (2276, 'Hardcoded string found')
  - (2281, 'Hardcoded string found')
  - (2286, 'Hardcoded string found')
  - (2291, 'Hardcoded string found')
  - (2296, 'Hardcoded string found')
  - (2301, 'Hardcoded string found')
  - (2306, 'Hardcoded string found')
  - (2311, 'Hardcoded string found')
  - (2316, 'Hardcoded string found')
  - (2321, 'Hardcoded string found')
  - (2326, 'Hardcoded string found')
  - (2331, 'Hardcoded string found')
  - (2336, 'Hardcoded string found')
  - (2341, 'Hardcoded string found')
  - (2346, 'Hardcoded string found')
  - (2351, 'Hardcoded string found')
  - (2356, 'Hardcoded string found')
  - (2361, 'Hardcoded string found')
  - (2366, 'Hardcoded string found')
  - (2371, 'Hardcoded string found')
  - (2376, 'Hardcoded string found')
  - (2381, 'Hardcoded string found')
  - (2386, 'Hardcoded string found')
  - (2391, 'Hardcoded string found')
  - (2396, 'Hardcoded string found')
  - (2401, 'Hardcoded string found')
  - (2406, 'Hardcoded string found')
  - (2411, 'Hardcoded string found')
  - (2416, 'Hardcoded string found')
  - (2421, 'Hardcoded string found')
  - (2426, 'Hardcoded string found')
  - (2431, 'Hardcoded string found')
  - (2436, 'Hardcoded string found')
  - (2441, 'Hardcoded string found')
  - (2446, 'Hardcoded string found')
  - (2451, 'Hardcoded string found')
  - (2456, 'Hardcoded string found')
  - (2461, 'Hardcoded string found')
  - (2466, 'Hardcoded string found')
  - (2471, 'Hardcoded string found')
  - (2476, 'Hardcoded string found')
  - (2481, 'Hardcoded string found')
  - (2486, 'Hardcoded string found')
  - (2491, 'Hardcoded string found')
  - (2496, 'Hardcoded string found')
  - (2501, 'Hardcoded string found')
  - (2506, 'Hardcoded string found')
  - (2511, 'Hardcoded string found')
  - (2516, 'Hardcoded string found')
  - (2521, 'Hardcoded string found')
  - (2526, 'Hardcoded string found')
  - (2531, 'Hardcoded string found')
  - (2536, 'Hardcoded string found')
  - (2541, 'Hardcoded string found')
  - (2546, 'Hardcoded string found')
  - (2551, 'Hardcoded string found')
  - (2556, 'Hardcoded string found')
  - (2561, 'Hardcoded string found')
  - (2566, 'Hardcoded string found')
Issues in app/client/tailwind.config.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
Issues in app/server/controllers/mainController.js:
  - (3, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
Issues in mobile/App.tsx:
  - (7, 'Hardcoded string found')
Issues in mobile/package-lock.json:
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
Issues in mobile/src/components/UI/Input.tsx:
  - (1, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in mobile/src/context/AuthContext.tsx:
  - (21, 'Line exceeds 80 characters')
Issues in mobile/src/navigation/RootNavigation.tsx:
  - (2, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Create/index.tsx:
  - (2, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/Restore/index.tsx:
  - (2, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
Issues in mobile/src/screens/Setup/WalletSetup.tsx:
  - (2, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
Issues in mobile/src/screens/Splash/Splash.tsx:
  - (2, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
Issues in mobile/src/utils/utils.ts:
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in mobile/tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
