### ISSUE TITLE
Issue-Buy, Sell, Cancel Buy, Cancel Sell

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#744]
Automated Review Comments
Issues in app/client/src/contexts/AuthContext.tsx:
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
Issues in app/client/src/pages/Trading/TradingAside.tsx:
  - (10, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (85, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
Issues in app/server/controllers/mainController.js:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
