### ISSUE TITLE
Issue-Update create page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#79]
Automated Review Comments
Issues in app/client/src/components/common/Input.tsx:
  - (1, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in app/client/src/components/common/Radio.tsx:
  - (2, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Create.tsx:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
Issues in app/client/src/pages/Login.tsx:
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
