### ISSUE TITLE
Issue-Create backup page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#81]
Automated Review Comments
Issues in app/client/src/components/common/Input.tsx:
  - (1, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Backup.tsx:
  - (2, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
Issues in app/client/src/pages/Create.tsx:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in app/client/src/routes/AppRoutes.tsx:
  - (1, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
