### ISSUE TITLE
Issue-Create confirm page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#83]
Automated Review Comments
Issues in app/client/src/pages/Confirm.tsx:
  - (2, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
