### ISSUE TITLE
Issue-Update backup page

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#85]
Automated Review Comments
Issues in app/client/src/pages/Backup.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
Issues in app/client/src/pages/Create.tsx:
  - (1, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
