### ISSUE TITLE
Issue-Complete basic create logic

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#91]
Automated Review Comments
Issues in app/client/src/components/common/Button.tsx:
  - (1, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
Issues in app/client/src/components/common/Input.tsx:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Backup.tsx:
  - (2, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
Issues in app/client/src/pages/Confirm.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Line exceeds 80 characters')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (94, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Line exceeds 80 characters')
  - (103, 'Hardcoded string found')
Issues in app/client/src/pages/Create.tsx:
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
Issues in app/client/src/redux/appSlice.ts:
  - (6, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
