### ISSUE TITLE
Issue-Check password available whil login

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#95]
Automated Review Comments
Issues in app/client/src/pages/Confirm.tsx:
  - (3, 'Hardcoded string found')
  - (4, 'Line exceeds 80 characters')
Issues in app/client/src/pages/Login.tsx:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (79, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (85, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (90, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
