### ISSUE TITLE
Issue-Create dashboard

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/wallet-qsilver#99]
Automated Review Comments
Issues in app/client/src/pages/Dashboard.tsx:
  - (5, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
Issues in app/client/src/routes/ProtectedRoute.tsx:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')

**Comment by ishida0415** [comment]
I got it.
